using System;
using System.Collections.Generic;

namespace AnnoDesigner.Localization
{
    public static class Localization
    {
        public static Dictionary<string, Dictionary<string, string>> Translations;

        static Localization()
        {
            //This dictionary initialisation was auto-generated from:
            //https://docs.google.com/spreadsheets/d/1CjECty43mkkm1waO4yhQl1rzZ-ZltrBgj00aq-WJX4w/edit?usp=sharing 
            //See the "Help" sheet for details on how to export the below dictionary.
            Translations = new Dictionary<string, Dictionary<string, string>>()
            {
                {
                    "eng", new Dictionary<string, string>() {
                        { "File" , "File" },
                        { "NewCanvas" , "New Canvas" },
                        { "Open" , "Open" },
                        { "Save" , "Save" },
                        { "SaveAs" , "Save As" },
                        { "CopyLayoutToClipboard" , "Copy layout to clipboard as JSON" },
                        { "LoadLayoutFromJson" , "Load layout from JSON" },
                        { "Exit" , "Exit" },
                        { "Extras" , "Extras" },
                        { "Normalize" , "Normalize" },
                        { "ResetZoom" , "Reset Zoom" },
                        { "RegisterFileExtension" , "Register File Extension" },
                        { "RegisterFileExtensionSuccessful" , "Registration of file extension was successful." },
                        { "UnregisterFileExtension" , "Unregister File Extension" },
                        { "UnregisterFileExtensionSuccessful" , "Deregistration of file extension was successful." },
                        { "Successful" , "Successful" },
                        { "Export" , "Export" },
                        { "ExportImage" , "Export Image" },
                        { "UseCurrentZoomOnExportedImage" , "Use current zoom on exported image" },
                        { "RenderSelectionHighlightsOnExportedImage" , "Render selection highlights on exported image" },
                        { "Language" , "Language" },
                        { "ManageStats" , "Manage Stats" },
                        { "ShowStats" , "Show Stats" },
                        { "BuildingCount" , "Building Count" },
                        { "Help" , "Help" },
                        { "Version" , "Version" },
                        { "FileVersion" , "File Version" },
                        { "PresetsVersion" , "Presets Version" },
                        { "CheckForUpdates" , "Check For Updates" },
                        { "EnableAutomaticUpdateCheck" , "Enable Automatic Update Check on Startup" },
                        { "GoToProjectHomepage" , "Go to Project Homepage" },
                        { "OpenWelcomePage" , "Open Welcome page" },
                        { "AboutAnnoDesigner" , "About Anno Designer" },
                        { "ShowGrid" , "Show Grid" },
                        { "ShowLabels" , "Show Labels" },
                        { "ShowIcons" , "Show Icons" },
                        { "ShowTrueInfluenceRange" , "Show True Influence Range" },
                        { "ShowInfluences" , "Show Influences" },
                        { "BuildingSettings" , "Building Settings" },
                        { "Size" , "Size" },
                        { "Color" , "Color" },
                        { "Label" , "Label" },
                        { "Icon" , "Icon" },
                        { "InfluenceType" , "Influence Type" },
                        { "None" , "None" },
                        { "Radius" , "Radius" },
                        { "Range" , "Range" },
                        { "Distance" , "Distance" },
                        { "Both" , "Both" },
                        { "PavedStreet" , "Paved Street" },
                        { "PavedStreetWarningTitle" , "Paved Street Selection" },
                        { "PavedStreetToolTip" , $"Checking this option will change the Influence Range for buildings, {Environment.NewLine}representing the increased range they receive when using paved streets.{Environment.NewLine}Use the 'Place Building' button to place an object." },
                        { "Options" , "Options" },
                        { "EnableLabel" , "Enable label" },
                        { "Borderless" , "Borderless" },
                        { "Road" , "Road" },
                        { "PlaceBuilding" , "Place building" },
                        { "Search" , "Search" },
                        { "SearchToolTip" , "ESC to clear search text" },
                        { "TitleAbout" , "About" },
                        { "BuildingLayoutDesigner" , "A building layout designer for Ubisofts Anno-series" },
                        { "Credits" , "Credits" },
                        { "OriginalApplicationBy" , "Original application by" },
                        { "BuildingPresets" , "Building presets" },
                        { "CombinedForAnnoVersions" , "Combined building presets for" },
                        { "AdditionalChanges" , "Additional changes by contributors on Github" },
                        { "ManyThanks" , "Many thanks to all the users who contributed to this project!" },
                        { "VisitTheFandom" , "Be sure to visit the Fandom pages for Anno!" },
                        { "OriginalHomepage" , "Original Homepage" },
                        { "ProjectHomepage" , "Project Homepage" },
                        { "GoToFandom" , "Go to Fandom" },
                        { "Close" , "Close" },
                        { "StatusBarControls" , "Mouse controls: left - place, select, move // right - stop placement, remove // both - move all // double click - copy // wheel - zoom // wheel-click - rotate." },
                        { "StatusBarItemsOnClipboard" , "Items on clipboard" },
                        { "StatNothingPlaced" , "Nothing Placed" },
                        { "StatBoundingBox" , "Bounding Box" },
                        { "StatMinimumArea" , "Minimum Area" },
                        { "StatSpaceEfficiency" , "Space Efficiency" },
                        { "StatBuildings" , "Buildings" },
                        { "StatBuildingsSelected" , "Buildings Selected" },
                        { "StatTiles" , "Tiles" },
                        { "StatNameNotFound" , "Building name not found" },
                        { "UnknownObject" , "Unknown Object" },
                        { "PresetsLoaded" , "Building presets loaded" },
                        { "ExportImageSuccessful" , "Image was successfully exported." },
                        { "ApplyColorToSelection" , "Apply color" },
                        { "ApplyColorToSelectionToolTip" , "Apply color to all buildings in current selection" },
                        { "ApplyPredefinedColorToSelection" , "Apply predefined color" },
                        { "ApplyPredefinedColorToSelectionToolTip" , "Apply predefined color (if found) to all buildings in current selection" },
                        { "AvailableColors" , "Available Colors" },
                        { "StandardColors" , "Predefined Colors" },
                        { "RecentColors" , "Recent used Colors" },
                        { "Standard" , "Standard" },
                        { "Advanced" , "Advanced" },
                        { "UpdateAvailableHeader" , "Update available" },
                        { "UpdateAvailablePresetMessage" , $"An updated version of the preset file is available.{Environment.NewLine}{Environment.NewLine}Do you want to download it and restart the application?" },
                        { "AdminRightsRequired" , "Admin rights required" },
                        { "UpdateRequiresAdminRightsMessage" , "To download the update the application needs write access. Please provide credentials." },
                        { "Error" , "Error" },
                        { "UpdateErrorPresetMessage" , "There was an error installing the update." },
                        { "UpdateNoConnectionMessage" , "Could not establish a connection to the internet." },
                        { "ColorsInLayout" , "Colors in Layout" },
                        { "ColorsInLayoutToolTip" , "Double click color to select it" },
                        { "LoadLayoutHeader" , "Load Layout" },
                        { "LoadLayoutMessage" , "Please paste the JSON string below." },
                        { "ClipboardContainsLayoutAsJson" , "Clipboard contains current layout as JSON." },
                        { "OK" , "OK" },
                        { "Cancel" , "Cancel" },
                        { "SelectAll" , "Select All" },
                        { "Tools" , "Tools" },
                        { "Preferences" , "Preferences" },
                        { "ResetAllConfirmationMessage" , "Are you sure you want to reset all hotkeys to their defaults?" },
                        { "ResetAll" , "Reset All" },
                        { "UpdateSettings" , "Update Settings" },
                        { "ManageKeybindings" , "Manage Keybindings" },
                        { "Rebind" , "Rebind" },
                        { "Recording" , "Recording" },
                        { "RecordANewAction" , "Record a new action" },
                        { "Rotate" , "Rotate" },
                        { "Copy" , "Copy" },
                        { "Paste" , "Paste" },
                        { "Delete" , "Delete" }
                    }
                },
                {
                    "ger", new Dictionary<string, string>() {
                        { "File" , "Datei" },
                        { "NewCanvas" , "Neue Oberfläche" },
                        { "Open" , "Öffnen" },
                        { "Save" , "Speichern" },
                        { "SaveAs" , "Speichern unter" },
                        { "CopyLayoutToClipboard" , "Layout als JSON in die Zwischenablage kopieren" },
                        { "LoadLayoutFromJson" , "Layout aus JSON laden" },
                        { "Exit" , "Beenden" },
                        { "Extras" , "Extras" },
                        { "Normalize" , "Normalisieren" },
                        { "ResetZoom" , "Zoom zurücksetzen" },
                        { "RegisterFileExtension" , "Dateierweiterung registrieren" },
                        { "RegisterFileExtensionSuccessful" , "Dateierweiterung wurde erfolgreich registriert." },
                        { "UnregisterFileExtension" , "Dateierweiterung entfernen" },
                        { "UnregisterFileExtensionSuccessful" , "Registrierung der Dateierweiterung wurde entfernt." },
                        { "Successful" , "Erfolg" },
                        { "Export" , "Exportieren" },
                        { "ExportImage" , "Exportiere Bild / Speichere als Bild" },
                        { "UseCurrentZoomOnExportedImage" , "Wende aktuellen Zomm auf exportiertes Bild an" },
                        { "RenderSelectionHighlightsOnExportedImage" , "Exportiere Bild mit Selektionen" },
                        { "Language" , "Sprache" },
                        { "ManageStats" , "Statistiken verwalten" },
                        { "ShowStats" , "Statistiken (an)zeigen" },
                        { "BuildingCount" , "Anzahl der Gebäude" },
                        { "Help" , "Hilfe" },
                        { "Version" , "Version" },
                        { "FileVersion" , "Dateiversion" },
                        { "PresetsVersion" , "Preset-Version" },
                        { "CheckForUpdates" , "Auf Updates prüfen" },
                        { "EnableAutomaticUpdateCheck" , "Automatische Updateprüfung beim Start aktivieren" },
                        { "GoToProjectHomepage" , "Gehe zu Projekt Startseite" },
                        { "OpenWelcomePage" , "Willkommensseite öffnen" },
                        { "AboutAnnoDesigner" , "über Anno Designer" },
                        { "ShowGrid" , "Raster/Gitter (an)zeigen" },
                        { "ShowLabels" , "Bezeichnungen (an)zeigen" },
                        { "ShowIcons" , "Symbol (an)zeigen" },
                        { "ShowTrueInfluenceRange" , "Wahren Einflussbereich anzeigen" },
                        { "ShowInfluences" , "Einflüsse anzeigen" },
                        { "BuildingSettings" , "Gebäude Optionen" },
                        { "Size" , "Größe" },
                        { "Color" , "Farbe" },
                        { "Label" , "Bezeichnung" },
                        { "Icon" , "Zeichen/Icon" },
                        { "InfluenceType" , "Einflusstyp" },
                        { "None" , "Keine" },
                        { "Radius" , "Radius" },
                        { "Range" , "Bereich" },
                        { "Distance" , "Entfernung" },
                        { "Both" , "Beide" },
                        { "PavedStreet" , "Gepflasterte Straße" },
                        { "PavedStreetWarningTitle" , "Auswahl der gepflasterten Straße" },
                        { "PavedStreetToolTip" , $"Wenn Sie diese Option aktivieren, wird der Einflussbereich für Gebäude geändert,{Environment.NewLine}die die erhöhte Reichweite darstellen, die sie bei der Nutzung gepflasterter Straßen erhalten.{Environment.NewLine}Verwenden Sie die Schaltfläche 'Gebäude platzieren', um ein Objekt zu platzieren." },
                        { "Options" , "Optionen" },
                        { "EnableLabel" , "Bezeichnung aktivieren" },
                        { "Borderless" , "Randlos" },
                        { "Road" , "Straße" },
                        { "PlaceBuilding" , "Gebäude platzieren" },
                        { "Search" , "Suche" },
                        { "SearchToolTip" , "ESC um Suchtext zu leeren" },
                        { "TitleAbout" , "über" },
                        { "BuildingLayoutDesigner" , "Ein Gebäudelayout Designer für Ubisofts Anno Reihe" },
                        { "Credits" , "Credits" },
                        { "OriginalApplicationBy" , "Ursprüngliche Anwendung von" },
                        { "BuildingPresets" , "Gebäudevorlagen" },
                        { "CombinedForAnnoVersions" , "Zusammengefügte Gebäudevorlagen für" },
                        { "AdditionalChanges" , "Weitere Änderungen von Beitragenden auf Github" },
                        { "ManyThanks" , "Vielen Dank an alle, die an diesem Projekt mitgeholfen haben!" },
                        { "VisitTheFandom" , "Besuche auch die Fandom Seiten von Anno!" },
                        { "OriginalHomepage" , "Original Startseite" },
                        { "ProjectHomepage" , "Projekt Startsteite" },
                        { "GoToFandom" , "Fandom Seite" },
                        { "Close" , "Schließen" },
                        { "StatusBarControls" , "Maussteuerung: Links - Platzieren, Auswählen, Verschieben // Rechts - Platzieren stoppen // Beide - Alle verschieben // Doppelklicken - Kopieren // Rad Zoom // Klickrad - Drehen" },
                        { "StatusBarItemsOnClipboard" , "Elemente in der Zwischenablage" },
                        { "StatNothingPlaced" , "Nichts platziert" },
                        { "StatBoundingBox" , "Begrenzungsbox" },
                        { "StatMinimumArea" , "Minimale Fläche" },
                        { "StatSpaceEfficiency" , "Raumeffizienz" },
                        { "StatBuildings" , "Gebäude" },
                        { "StatBuildingsSelected" , "Ausgewählte Gebäude" },
                        { "StatTiles" , "Kacheln" },
                        { "StatNameNotFound" , "Gebäudename nicht gefunden" },
                        { "UnknownObject" , "Unbekanntes Objekt" },
                        { "PresetsLoaded" , "Gebäudevorlagen geladen" },
                        { "ExportImageSuccessful" , "Das Bild wurde erfolgreich exportiert." },
                        { "ApplyColorToSelection" , "Farbe anwenden" },
                        { "ApplyColorToSelectionToolTip" , "Farbe auf alle Gebäude in der aktuellen Auswahl anwenden" },
                        { "ApplyPredefinedColorToSelection" , "Vordefinierte Farbe anwenden" },
                        { "ApplyPredefinedColorToSelectionToolTip" , "Vordefinierte Farbe (falls gefunden) auf alle Gebäude in der aktuellen Auswahl anwenden." },
                        { "AvailableColors" , "Verfügbare Farben" },
                        { "StandardColors" , "Vordefinierte Farben" },
                        { "RecentColors" , "Zuletzt verwendete Farben" },
                        { "Standard" , "Standard" },
                        { "Advanced" , "Erweitert" },
                        { "UpdateAvailableHeader" , "Update verfügbar" },
                        { "UpdateAvailablePresetMessage" , $"Eine aktualisierte Version der Vorlagen ist verfügbar.{Environment.NewLine}{Environment.NewLine}Möchten Sie sie herunterladen und die Anwendung neu starten?" },
                        { "AdminRightsRequired" , "Admin-Rechte erforderlich" },
                        { "UpdateRequiresAdminRightsMessage" , "Um das Update herunterzuladen, benötigt die Anwendung Schreibzugriff. Bitte geben Sie die Zugangsdaten an." },
                        { "Error" , "Fehler" },
                        { "UpdateErrorPresetMessage" , "Es gab einen Fehler bei der Installation des Updates." },
                        { "UpdateNoConnectionMessage" , "Es konnte keine Verbindung zum Internet hergestellt werden." },
                        { "ColorsInLayout" , "Farben im Layout" },
                        { "ColorsInLayoutToolTip" , "Doppelklicken Sie auf die Farbe, um sie auszuwählen." },
                        { "LoadLayoutHeader" , "Layout laden" },
                        { "LoadLayoutMessage" , "Bitte fügen Sie die JSON-Zeichenkette unten ein." },
                        { "ClipboardContainsLayoutAsJson" , "Die Zwischenablage enthält das aktuelle Layout als JSON." },
                        { "OK" , "OK" },
                        { "Cancel" , "Abbrechen" },
                        { "SelectAll" , "Alle auswählen" },
                        { "Tools" , "Werkzeuge" },
                        { "Preferences" , "Präferenzen" },
                        { "ResetAllConfirmationMessage" , "Sind Sie sicher, dass Sie alle Hotkeys auf ihre Standardeinstellungen zurücksetzen möchten?" },
                        { "ResetAll" , "Alle zurücksetzen" },
                        { "UpdateSettings" , "Update-Einstellungen" },
                        { "ManageKeybindings" , "Schlüsselbindungen verwalten" },
                        { "Rebind" , "Neu binden" },
                        { "Recording" , "Aufzeichnung" },
                        { "RecordANewAction" , "Eine neue Aktion aufzeichnen" },
                        { "Rotate" , "Rotieren" },
                        { "Copy" , "Kopie" },
                        { "Paste" , "Einfügen" },
                        { "Delete" , "löschen" }
                    }
                },
                {
                    "fra", new Dictionary<string, string>() {
                        { "File" , "Fichier" },
                        { "NewCanvas" , "Nouveau projet" },
                        { "Open" , "Ouvrir" },
                        { "Save" , "Sauvegarder" },
                        { "SaveAs" , "Sauvegarder sous" },
                        { "CopyLayoutToClipboard" , "Copier la mise en page dans le presse-papiers en tant que JSON" },
                        { "LoadLayoutFromJson" , "Charger l'agencement à partir de JSON" },
                        { "Exit" , "Quitter" },
                        { "Extras" , "Extras" },
                        { "Normalize" , "Centrer" },
                        { "ResetZoom" , "Rénitialiser le zoom" },
                        { "RegisterFileExtension" , "Enregistrer l'extension du fichier" },
                        { "RegisterFileExtensionSuccessful" , "L'enregistrement de l'extension du fichier est terminée" },
                        { "UnregisterFileExtension" , "Supprimer l'extension du fichier" },
                        { "UnregisterFileExtensionSuccessful" , "La suppresion de l'extension du fichier est terminée" },
                        { "Successful" , "Réussi" },
                        { "Export" , "Exporter" },
                        { "ExportImage" , "Exporter une image" },
                        { "UseCurrentZoomOnExportedImage" , "Utiliser le zom actuel sur l'image exportée" },
                        { "RenderSelectionHighlightsOnExportedImage" , "Rendre la sélection en surbrillance sur l'image exportée" },
                        { "Language" , "Langue" },
                        { "ManageStats" , "Gérer les statistiques" },
                        { "ShowStats" , "Montrer les statistiques" },
                        { "BuildingCount" , "Nombre de bâtiment" },
                        { "Help" , "Aide" },
                        { "Version" , "Version" },
                        { "FileVersion" , "Version du fichier" },
                        { "PresetsVersion" , "Version du préréglage" },
                        { "CheckForUpdates" , "Vérifiez les mises à jour" },
                        { "EnableAutomaticUpdateCheck" , "Activer les mises à jour automatique au démarrage" },
                        { "GoToProjectHomepage" , "Visiter le site internet du projet" },
                        { "OpenWelcomePage" , "Ouvrir la page d'accueil" },
                        { "AboutAnnoDesigner" , "À propos d'Anno Designer" },
                        { "ShowGrid" , "Montrez le quadrillage" },
                        { "ShowLabels" , "Montrez les étiquettes" },
                        { "ShowIcons" , "Montrez les icônes" },
                        { "ShowTrueInfluenceRange" , "Montrer l'étendue de l'influence réelle" },
                        { "ShowInfluences" , "Montrez vos influences" },
                        { "BuildingSettings" , "Paramètres de construction" },
                        { "Size" , "Grandeur" },
                        { "Color" , "Couleur" },
                        { "Label" , "Étiquette" },
                        { "Icon" , "Icône" },
                        { "InfluenceType" , "Type d'influence" },
                        { "None" , "Aucun" },
                        { "Radius" , "Rayon" },
                        { "Range" , "Zone de détection" },
                        { "Distance" , "Distance" },
                        { "Both" , "Tous les deux" },
                        { "PavedStreet" , "Rue pavée" },
                        { "PavedStreetWarningTitle" , "Sélection de rues pavées" },
                        { "PavedStreetToolTip" , $"Si vous cochez cette option, la plage d'influence des bâtiments sera modifiée, {Environment.NewLine}ce qui représente la portée accrue qu'ils reçoivent lorsqu'ils utilisent des rues pavées.{Environment.NewLine}Utilisez le bouton 'Placer le bâtiment' pour placer l'objet." },
                        { "Options" , "Options" },
                        { "EnableLabel" , "Activer les étiquettes" },
                        { "Borderless" , "Sans bordure" },
                        { "Road" , "Routes" },
                        { "PlaceBuilding" , "Placer le bâtiment" },
                        { "Search" , "Rechercher" },
                        { "SearchToolTip" , "ESC pour effacer la recherche" },
                        { "TitleAbout" , "À propos" },
                        { "BuildingLayoutDesigner" , "Un planificateur de carte pour la série Anno d'Ubisofts" },
                        { "Credits" , "Crédits" },
                        { "OriginalApplicationBy" , "Application originale par" },
                        { "BuildingPresets" , "prédisposition des bâtiments" },
                        { "CombinedForAnnoVersions" , "Combiner les prédispositions des bâtiments pour" },
                        { "AdditionalChanges" , "Changements supplémentaires par les contributeurs sur Github" },
                        { "ManyThanks" , "Un énorme merci à tous les utilisateurs qui ont contribués au projet!" },
                        { "VisitTheFandom" , "Assurez-vous de visiter la page de Fandom pour Anno!" },
                        { "OriginalHomepage" , "Page originale" },
                        { "ProjectHomepage" , "Page du projet" },
                        { "GoToFandom" , "Site internet de Fandom" },
                        { "Close" , "Fermer" },
                        { "StatusBarControls" , "Contrôles de la souris: gauche - placer, sélectionner, déplacer // droit – arrêter le déplacement, retirer // les deux – tout déplacer // double clic - copier // molette - zoom // clic de la molette - rotation." },
                        { "StatusBarItemsOnClipboard" , "Éléments dans le presse-papier" },
                        { "StatNothingPlaced" , "Rien n'est placé" },
                        { "StatBoundingBox" , "Zone de délimitation" },
                        { "StatMinimumArea" , "Surface minimale" },
                        { "StatSpaceEfficiency" , "Utilisation de l'espace" },
                        { "StatBuildings" , "Bâtiments" },
                        { "StatBuildingsSelected" , "Bâtiment sélectionné" },
                        { "StatTiles" , "Carrelage" },
                        { "StatNameNotFound" , "Nom du bâtiment introuvable" },
                        { "UnknownObject" , "Object inconnu" },
                        { "PresetsLoaded" , "Préréglage du bâtiment importé" },
                        { "ExportImageSuccessful" , "L'image a été exportée correctement." },
                        { "ApplyColorToSelection" , "Appliquer la couleur" },
                        { "ApplyColorToSelectionToolTip" , "Appliquer la couleur à tous les bâtiments de la sélection courante" },
                        { "ApplyPredefinedColorToSelection" , "Appliquer la couleur prédéfinie" },
                        { "ApplyPredefinedColorToSelectionToolTip" , "Appliquer la couleur prédéfinie (si trouvée) à tous les bâtiments de la sélection courante" },
                        { "AvailableColors" , "Couleurs disponibles" },
                        { "StandardColors" , "Couleurs prédéfinies" },
                        { "RecentColors" , "Couleurs utilisées récemment" },
                        { "Standard" , "Standard" },
                        { "Advanced" , "Avancé" },
                        { "UpdateAvailableHeader" , "Mise à jour disponible" },
                        { "UpdateAvailablePresetMessage" , $"Une version mise à jour des préréglages est disponible.{Environment.NewLine}{Environment.NewLine}Voulez-vous le télécharger et redémarrer l'application?" },
                        { "AdminRightsRequired" , "Droits d'administration requis" },
                        { "UpdateRequiresAdminRightsMessage" , "Pour télécharger la mise à jour, l'application a besoin d'un accès en écriture. Veuillez fournir vos justificatifs d'identité." },
                        { "Error" , "Erreur" },
                        { "UpdateErrorPresetMessage" , "Il y a eu une erreur lors de l'installation de la mise à jour." },
                        { "UpdateNoConnectionMessage" , "Impossible d'établir une connexion à Internet." },
                        { "ColorsInLayout" , "Couleurs dans la mise en page" },
                        { "ColorsInLayoutToolTip" , "Double-cliquez sur la couleur pour la sélectionner" },
                        { "LoadLayoutHeader" , "Disposition de la charge" },
                        { "LoadLayoutMessage" , "Veuillez coller la chaîne JSON ci-dessous." },
                        { "ClipboardContainsLayoutAsJson" , "Le presse-papiers contient la mise en page actuelle en tant que JSON." },
                        { "OK" , "OK" },
                        { "Cancel" , "Annuler" },
                        { "SelectAll" , "Sélectionner tout" },
                        { "Tools" , "Outils" },
                        { "Preferences" , "Préférences" },
                        { "ResetAllConfirmationMessage" , "Êtes-vous sûr de vouloir réinitialiser toutes les touches de raccourci à leurs paramètres par défaut ?" },
                        { "ResetAll" , "Réinitialiser tout" },
                        { "UpdateSettings" , "Mise à jour des paramètres" },
                        { "ManageKeybindings" , "Gérer les porte-clés" },
                        { "Rebind" , "Relier" },
                        { "Recording" , "Enregistrement" },
                        { "RecordANewAction" , "Enregistrer une nouvelle action" },
                        { "Rotate" , "Faire tourner" },
                        { "Copy" , "Copie" },
                        { "Paste" , "Coller" },
                        { "Delete" , "Supprimer" }
                    }
                },
                {
                    "pol", new Dictionary<string, string>() {
                        { "File" , "Plik" },
                        { "NewCanvas" , "Nowy projekt" },
                        { "Open" , "Otwórz" },
                        { "Save" , "Zapisz" },
                        { "SaveAs" , "Zapisz jako" },
                        { "CopyLayoutToClipboard" , "Skopiuj układ do schowka jako JSON." },
                        { "LoadLayoutFromJson" , "Układ obciążenia od JSON" },
                        { "Exit" , "Zamknij" },
                        { "Extras" , "Dodatki" },
                        { "Normalize" , "Znormalizuj" },
                        { "ResetZoom" , "Resetuj powiększenie" },
                        { "RegisterFileExtension" , "Zarejestruj rozszerzenie pliku" },
                        { "RegisterFileExtensionSuccessful" , "Rejestracja rozszerzenia pliku zakończyła się sukcesem." },
                        { "UnregisterFileExtension" , "Wyrejestruj rozszerzenie pliku" },
                        { "UnregisterFileExtensionSuccessful" , "Wyrejestrowanie rozszerzenia pliku zakończyło się sukcesem." },
                        { "Successful" , "Udało się." },
                        { "Export" , "Eksportuj" },
                        { "ExportImage" , "Eksportuj obraz" },
                        { "UseCurrentZoomOnExportedImage" , "Użyj obecnego powiększenia na eksportowanym obrazie" },
                        { "RenderSelectionHighlightsOnExportedImage" , "Pokaż podświetlenie wybranych elementów na eksportowanym obrazie" },
                        { "Language" , "Język" },
                        { "ManageStats" , "Zarządzanie statystyki" },
                        { "ShowStats" , "Pokaż statystyki" },
                        { "BuildingCount" , "Licznik budynków" },
                        { "Help" , "Pomoc" },
                        { "Version" , "Wersja" },
                        { "FileVersion" , "Wersja pliku" },
                        { "PresetsVersion" , "Presety-wersja" },
                        { "CheckForUpdates" , "Sprawdź aktualizacje" },
                        { "EnableAutomaticUpdateCheck" , "Włączyć automatyczne sprawdzanie aktualizacji przy uruchamianiu" },
                        { "GoToProjectHomepage" , "Przejdź do strony projektu" },
                        { "OpenWelcomePage" , "Otwórz stronę powitalną" },
                        { "AboutAnnoDesigner" , "O Anno Designerze" },
                        { "ShowGrid" , "Pokaż siatkę" },
                        { "ShowLabels" , "Pokaż etykiety" },
                        { "ShowIcons" , "Pokaż ikony" },
                        { "ShowTrueInfluenceRange" , "Pokaż prawdziwy zakres wpływu" },
                        { "ShowInfluences" , "Pokaż wpływy" },
                        { "BuildingSettings" , "Ustawienia budynku" },
                        { "Size" , "Wymiary" },
                        { "Color" , "Kolor" },
                        { "Label" , "Podpis" },
                        { "Icon" , "Ikona" },
                        { "InfluenceType" , "Rodzaj wpływu Typ" },
                        { "None" , "Nie ma" },
                        { "Radius" , "Promień" },
                        { "Range" , "Zasięg" },
                        { "Distance" , "Odległość" },
                        { "Both" , "Obydwoje" },
                        { "PavedStreet" , "Droga Brukowana" },
                        { "PavedStreetWarningTitle" , "Wybór Drogi Brukowanej" },
                        { "PavedStreetToolTip" , $"Zaznaczenie tej opcji spowoduje zmianę zakresu wpływu dla budynków, {Environment.NewLine}reprezentujący zwiększony zasięg, jaki otrzymują, gdy używając brukowanych ulic.{Environment.NewLine}Użyj przycisku 'Postaw budynek', aby umieścić obiekt." },
                        { "Options" , "Opcje" },
                        { "EnableLabel" , "Pokaż etykietę" },
                        { "Borderless" , "Bez obramowania" },
                        { "Road" , "Droga / Ulica" },
                        { "PlaceBuilding" , "Postaw budynek" },
                        { "Search" , "Wyszukiwanie" },
                        { "SearchToolTip" , "ESC aby wyczyścić tekst do przeszukiwania" },
                        { "TitleAbout" , "Na temat / O" },
                        { "BuildingLayoutDesigner" , "Program do planowania zabudowy w serii Anno Ubisoftu" },
                        { "Credits" , "Autorzy" },
                        { "OriginalApplicationBy" , "Oryginalna aplikacja napisana przez" },
                        { "BuildingPresets" , "Presety dla budynków" },
                        { "CombinedForAnnoVersions" , "Połączone presety budynków dla" },
                        { "AdditionalChanges" , "Dodatkowe zmiany wprowadzone przez płatników w sprawie Github" },
                        { "ManyThanks" , "Dziękujemy wszystkim użytkownikom, którzy wsparli ten projekt!" },
                        { "VisitTheFandom" , "Odwiedź fanowskie strony o Anno!" },
                        { "OriginalHomepage" , "Oryginalna strona" },
                        { "ProjectHomepage" , "Strona projektu" },
                        { "GoToFandom" , "Przejdź do strony Fandom" },
                        { "Close" , "Zamknij" },
                        { "StatusBarControls" , "Sterowanie myszą: w lewo - miejsce, zaznacz, przesuń // zatrzymanie w prawo, usuń // oba - przenieś wszystko // podwójne kliknięcie - kopiuj // kółko - powiększ // kółko - obracaj." },
                        { "StatusBarItemsOnClipboard" , "pozycje w schowku" },
                        { "StatNothingPlaced" , "Nic nie postawiono" },
                        { "StatBoundingBox" , "Ramka Ograniczająca" },
                        { "StatMinimumArea" , "Minimalna Powierzchnia" },
                        { "StatSpaceEfficiency" , "Wykorzystanie Przestrzeni" },
                        { "StatBuildings" , "Budynki" },
                        { "StatBuildingsSelected" , "Wybrane Budynki" },
                        { "StatTiles" , "Płytki" },
                        { "StatNameNotFound" , "Nie znaleziono nazwy budynku" },
                        { "UnknownObject" , "Obiekt nieznany" },
                        { "PresetsLoaded" , "Presety budynków załadowano" },
                        { "ExportImageSuccessful" , "Obraz został pomyślnie wyeksportowany." },
                        { "ApplyColorToSelection" , "Zastosuj kolor" },
                        { "ApplyColorToSelectionToolTip" , "Zastosowanie koloru do wszystkich budynków w bieżącym wyborze" },
                        { "ApplyPredefinedColorToSelection" , "Zastosuj predefiniowany kolor" },
                        { "ApplyPredefinedColorToSelectionToolTip" , "Zastosuj predefiniowany kolor (jeśli został znaleziony) do wszystkich budynków w bieżącym wyborze." },
                        { "AvailableColors" , "Dostępne kolory" },
                        { "StandardColors" , "Predefiniowane kolory" },
                        { "RecentColors" , "Ostatnio używane kolory" },
                        { "Standard" , "Standard" },
                        { "Advanced" , "Zaawansowane" },
                        { "UpdateAvailableHeader" , "Dostępna aktualizacja" },
                        { "UpdateAvailablePresetMessage" , $"Dostępna jest zaktualizowana wersja presetów.{Environment.NewLine}{Environment.NewLine}Chcesz ją pobrać i zrestartować aplikację?" },
                        { "AdminRightsRequired" , "Wymagane prawa administratora" },
                        { "UpdateRequiresAdminRightsMessage" , "Aby pobrać aktualizację, aplikacja musi mieć dostęp do zapisu. Proszę podać dane uwierzytelniające." },
                        { "Error" , "Błąd" },
                        { "UpdateErrorPresetMessage" , "Wystąpił błąd podczas instalacji aktualizacji." },
                        { "UpdateNoConnectionMessage" , "Nie udało się nawiązać połączenia z Internetem." },
                        { "ColorsInLayout" , "Kolory w układzie" },
                        { "ColorsInLayoutToolTip" , "Podwójne kliknięcie na kolor, aby go wybrać" },
                        { "LoadLayoutHeader" , "Układ obciążenia" },
                        { "LoadLayoutMessage" , "Proszę wkleić poniższy ciąg JSON." },
                        { "ClipboardContainsLayoutAsJson" , "Schowek zawiera aktualny układ jako JSON." },
                        { "OK" , "OK" },
                        { "Cancel" , "Odwołaj" },
                        { "SelectAll" , "Wybierz wszystkie" },
                        { "Tools" , "Narzędzia" },
                        { "Preferences" , "Preferencje" },
                        { "ResetAllConfirmationMessage" , "Czy na pewno chcesz zresetować wszystkie klawisze funkcyjne do ich domyślnych ustawień?" },
                        { "ResetAll" , "Zresetuj wszystko" },
                        { "UpdateSettings" , "Ustawienia aktualizacji" },
                        { "ManageKeybindings" , "Zarządzanie klawiaturami" },
                        { "Rebind" , "Powiąż ponownie" },
                        { "Recording" , "Nagranie" },
                        { "RecordANewAction" , "Zapisać nową akcję" },
                        { "Rotate" , "Obróć" },
                        { "Copy" , "Kopia" },
                        { "Paste" , "Pasta" },
                        { "Delete" , "Skreślić" }
                    }
                },
                {
                    "rus", new Dictionary<string, string>() {
                        { "File" , "Файл" },
                        { "NewCanvas" , "Новый файл" },
                        { "Open" , "Открыть" },
                        { "Save" , "Сохранить" },
                        { "SaveAs" , "Сохранить как" },
                        { "CopyLayoutToClipboard" , "Скопировать макет в буфер обмена как JSON" },
                        { "LoadLayoutFromJson" , "Схема загрузки от JSON" },
                        { "Exit" , "Выход" },
                        { "Extras" , "Дополнительно" },
                        { "Normalize" , "Нормализация" },
                        { "ResetZoom" , "Сбросить масштаб" },
                        { "RegisterFileExtension" , "Зарегистрировать расширение файла" },
                        { "RegisterFileExtensionSuccessful" , "Регистрация расширения файла прошла успешно." },
                        { "UnregisterFileExtension" , "Отмена регистрации расширения файла" },
                        { "UnregisterFileExtensionSuccessful" , "Отмена регистрации продления файлов прошла успешно." },
                        { "Successful" , "Успешный" },
                        { "Export" , "Экспорт" },
                        { "ExportImage" , "Экспортировать изображение" },
                        { "UseCurrentZoomOnExportedImage" , "Использовать текущее масштабирование экспортируемого изображения" },
                        { "RenderSelectionHighlightsOnExportedImage" , "Выделение выделенного фрагмента на экспортируемом изображении" },
                        { "Language" , "язык" },
                        { "ManageStats" , "Управление статистикой" },
                        { "ShowStats" , "Показывать параметры" },
                        { "BuildingCount" , "Строительный граф" },
                        { "Help" , "Помощь" },
                        { "Version" , "Версия" },
                        { "FileVersion" , "Версия файла" },
                        { "PresetsVersion" , "Версия пресета" },
                        { "CheckForUpdates" , "Проверить наличие обновлений" },
                        { "EnableAutomaticUpdateCheck" , "Включить автоматическую проверку обновлений при запуске" },
                        { "GoToProjectHomepage" , "Перейти на главную страницу" },
                        { "OpenWelcomePage" , "Открыть страницу приветствия" },
                        { "AboutAnnoDesigner" , "О Anno Дизайнер" },
                        { "ShowGrid" , "Показать сетку" },
                        { "ShowLabels" , "Показывать название" },
                        { "ShowIcons" , "Показывать значок" },
                        { "ShowTrueInfluenceRange" , "Показать истинный диапазон влияния" },
                        { "ShowInfluences" , "Показать влияние" },
                        { "BuildingSettings" , "Параметры здания" },
                        { "Size" , "Размер" },
                        { "Color" , "Цвет" },
                        { "Label" , "Название" },
                        { "Icon" , "Значок" },
                        { "InfluenceType" , "Тип влияния" },
                        { "None" , "Нет" },
                        { "Radius" , "Радиус" },
                        { "Range" , "Диапазон" },
                        { "Distance" , "Расстояние" },
                        { "Both" , "Оба" },
                        { "PavedStreet" , "Павед Стрит" },
                        { "PavedStreetWarningTitle" , "Выбор улицы Павед Стрит" },
                        { "PavedStreetToolTip" , $"Установив этот флажок, можно изменить диапазон влияния для зданий,{Environment.NewLine}представляет собой увеличенную дальность, которую они получают при использовании мощеных улиц.{Environment.NewLine}Используйте кнопку 'Выбрать здание', чтобы поместить объект." },
                        { "Options" , "Параметры" },
                        { "EnableLabel" , "Показывать название" },
                        { "Borderless" , "Без полей" },
                        { "Road" , "Дорогa" },
                        { "PlaceBuilding" , "Выбрать здание" },
                        { "Search" , "Поиск" },
                        { "SearchToolTip" , "ESC чтобы очистить текст поиска" },
                        { "TitleAbout" , "О программе" },
                        { "BuildingLayoutDesigner" , "Конструктор макета здания для Ubisofts Anno-серии" },
                        { "Credits" , "Авторы" },
                        { "OriginalApplicationBy" , "Оригинальное приложение" },
                        { "BuildingPresets" , "Строительные пресеты" },
                        { "CombinedForAnnoVersions" , "Комбинированные строительные пресеты для" },
                        { "AdditionalChanges" , "Дополнительные изменения по вкладчикам на Github" },
                        { "ManyThanks" , "Большое спасибо всем пользователям, которые внесли свой вклад в этот проект!" },
                        { "VisitTheFandom" , "Обязательно посетите страницы Фэндома для Anno!" },
                        { "OriginalHomepage" , "Оригинальная домашняя страница" },
                        { "ProjectHomepage" , "Домашняя страница проекта" },
                        { "GoToFandom" , "Перейти к Фэндом" },
                        { "Close" , "Закрыть" },
                        { "StatusBarControls" , "Управление мышью: влево - разместить, выбрать, переместить // вправо - прекратить размещение, удалить // оба - переместить все // двойной щелчок - копировать // колесо - масштабировать // колесико щелкнуть - повернуть." },
                        { "StatusBarItemsOnClipboard" , "элементы в буфере обмена" },
                        { "StatNothingPlaced" , "Ничего не размещено" },
                        { "StatBoundingBox" , "Ограничительная рамка" },
                        { "StatMinimumArea" , "Минимальная площадь" },
                        { "StatSpaceEfficiency" , "Космическая эффективность" },
                        { "StatBuildings" , "Здания" },
                        { "StatBuildingsSelected" , "Выбранные здания" },
                        { "StatTiles" , "Плитка" },
                        { "StatNameNotFound" , "Название здания не найдено" },
                        { "UnknownObject" , "Неизвестный объект" },
                        { "PresetsLoaded" , "Загружаются пресеты зданий" },
                        { "ExportImageSuccessful" , "Изображение было успешно экспортировано." },
                        { "ApplyColorToSelection" , "Применить цвет" },
                        { "ApplyColorToSelectionToolTip" , "Применить цвет ко всем зданиям в текущем выборе" },
                        { "ApplyPredefinedColorToSelection" , "Применить предопределенный цвет" },
                        { "ApplyPredefinedColorToSelectionToolTip" , "Применить предопределенный цвет (если он найден) ко всем зданиям в текущем выборе." },
                        { "AvailableColors" , "Доступные цвета" },
                        { "StandardColors" , "Предварительно определенные цвета" },
                        { "RecentColors" , "Последние использованные цвета" },
                        { "Standard" , "Стандарт" },
                        { "Advanced" , "Расширенный" },
                        { "UpdateAvailableHeader" , "Обновление доступно" },
                        { "UpdateAvailablePresetMessage" , $"Доступна обновленная версия предустановок.{Environment.NewLine}{Environment.NewLine}Вы хотите скачать его и перезапустить приложение?" },
                        { "AdminRightsRequired" , "Требуемые права администратора" },
                        { "UpdateRequiresAdminRightsMessage" , "Для загрузки обновления приложению необходим доступ на запись. Пожалуйста, предоставьте полномочия." },
                        { "Error" , "Ошибка" },
                        { "UpdateErrorPresetMessage" , "Произошла ошибка при установке обновления." },
                        { "UpdateNoConnectionMessage" , "Не смог установить соединение с интернетом." },
                        { "ColorsInLayout" , "Цвета в макетах" },
                        { "ColorsInLayoutToolTip" , "Дважды щелкните по цвету, чтобы выбрать его." },
                        { "LoadLayoutHeader" , "Загрузить макет" },
                        { "LoadLayoutMessage" , "Пожалуйста, вставьте JSON строку ниже." },
                        { "ClipboardContainsLayoutAsJson" , "Буфер обмена содержит текущую верстку в виде JSON." },
                        { "OK" , "OK" },
                        { "Cancel" , "Отмена" },
                        { "SelectAll" , "Выберите все" },
                        { "Tools" , "Инструменты" },
                        { "Preferences" , "Предпочтения" },
                        { "ResetAllConfirmationMessage" , "Вы уверены, что хотите сбросить все горячие клавиши в их настройки по умолчанию?" },
                        { "ResetAll" , "Сбросить все" },
                        { "UpdateSettings" , "Обновление Настройки" },
                        { "ManageKeybindings" , "Управление привязками к ключам" },
                        { "Rebind" , "Перезаписать" },
                        { "Recording" , "Запись" },
                        { "RecordANewAction" , "Записать новое действие" },
                        { "Rotate" , "Повернуть" },
                        { "Copy" , "Скопировать" },
                        { "Paste" , "Вставить" },
                        { "Delete" , "Удалить" }
                    }
                },
            };
        }

        public static readonly Dictionary<string, string> LanguageCodeMap = new Dictionary<string, string>()
        {
            { "English", "eng" },
            { "Deutsch", "ger" },
            { "Français","fra" },
            { "Español", "esp" },
            { "Italiano", "ita" },
            { "Polski", "pol" },
            { "Русский", "rus" },
            { "český", "cze" },
        };

        public static string GetLanguageCodeFromName(string s)
        {
            return LanguageCodeMap[s];
        }

        public static void Update()
        {

        }
    }
}


