using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;

namespace AnnoDesigner.TreeLocalization
{
    public static class TreeLocalization
    {
        public static Dictionary<string, Dictionary<string, string>> Translations;

        static TreeLocalization()
        {
            //This dictionary initialisation can be find on :
            //https://docs.google.com/spreadsheets/d/1CjECty43mkkm1waO4yhQl1rzZ-ZltrBgj00aq-WJX4w/edit?usp=sharing 
            //Steps to format:
            //Run CreateDictionary Script
            //Copy Output
            //Replace the escaped characters (\t\r\n) with the actual characters from within an editor of your choice
            Translations = new Dictionary<string, Dictionary<string, string>>()
            {
                {
                    "eng", new Dictionary<string, string>() {
                        { "Military" , "Military" },
                        { "Camps" , "Camps" },
                        { "Production" , "Production" },
                        { "Ornament" , "Ornaments" },
                        { "ManorialPalace" , "Manorial Palace" },
                        { "PlayerBuildings" , "Player Buildings" },
                        { "Harbour" , "Harbour" },
                        { "Harbor" , "Harbour" },
                        { "Residence" , "Residence" },
                        { "Animalfarm" , "Animalfarm" },
                        { "Factory" , "Factory" },
                        { "Farm" , "Farm" },
                        { "FarmFields" , "Farm Fields" },
                        { "Plantation" , "Plantation" },
                        { "Resource" , "Resource" },
                        { "Public" , "Public Buildings" },
                        { "PublicBuildings" , "Public Buildings" },
                        { "Demand" , "Demand" },
                        { "Marine" , "Marine" },
                        { "Special" , "Special" },
                        { "Trade" , "Trade" },
                        { "(1)Ecos" , "(1) Ecos" },
                        { "(2)Tycoons" , "(2) Tycoons" },
                        { "(3)Techs" , "(3) Techs" },
                        { "Others" , "Others" },
                        { "Energy" , "Energy" },
                        { "BlackSmokers(DeepSea)" , "Black Smokers (Deep Sea)" },
                        { "BlackSmokers(Normal)" , "Black Smokers (Normal)" },
                        { "(1)Earth" , "(1) Earth" },
                        { "(2)Arctic" , "(2) Arctic" },
                        { "(3)Moon" , "(3) Moon" },
                        { "(4)Tundra" , "(4) Tundra" },
                        { "(5)Orbit" , "(5) Orbit" },
                        { "Facilities" , "Facilities" },
                        { "Ornaments" , "Ornaments" },
                        { "GlobalModules" , "Global Modules" },
                        { "Laboratories" , "Laboratories" },
                        { "Modules" , "Modules" },
                        { "Agriculture" , "Agriculture" },
                        { "Biotech" , "Biotech" },
                        { "Chemical" , "Chemical" },
                        { "Electronics" , "Electronics" },
                        { "Food" , "Food" },
                        { "Heavy" , "Heavy" },
                        { "Mining" , "Mining" },
                        { "TundraModules" , "Tundra Modules" },
                        { "IndustryModules" , "Industry Modules" },
                        { "CentralTechUnitReactor" , "Central Tech Unit Reactor" },
                        { "(1)Farmers" , "(1) Farmers" },
                        { "(2)Workers" , "(2) Workers" },
                        { "(3)Artisans" , "(3) Artisans" },
                        { "(4)Engineers" , "(4) Engineers" },
                        { "(5)Investors" , "(5) Investors" },
                        { "(6)OldWorldFields" , "(6) Old World Fields" },
                        { "(7)Jornaleros" , "(7) Jornaleros" },
                        { "(8)Obreros" , "(8) Obreros" },
                        { "(9)NewWorldFields" , "(9) New World Fields" },
                        { "AllWorlds" , "All Worlds" },
                        { "Attractiveness" , "Attractiveness" },
                        { "Electricity" , "Electricity" },
                        { "FarmBuildings" , "Farm Buildings" },
                        { "ProductionBuildings" , "Production Buildings" },
                        { "Depots" , "Depots" },
                        { "Logistics" , "Logistics" },
                        { "Shipyards" , "Shipyards" },
                        { "SpecialBuildings" , "Special Buildings" },
                        { "MiningBuildings" , "Mining Buildings" },
                        { "OrnamentalBuildings" , "Ornaments" },
                    }
                    },
                {
                    "ger", new Dictionary<string, string>() {
                        { "Military" , "Militär" },
                        { "Camps" , "Lager" },
                        { "Production" , "Produktion" },
                        { "Ornament" , "Ornamente" },
                        { "ManorialPalace" , "Herrschaftspalast" },
                        { "PlayerBuildings" , "Spielergebäude" },
                        { "Harbour" , "Hafen" },
                        { "Harbor" , "Hafen" },
                        { "Residence" , "Wohnsitz" },
                        { "Animalfarm" , "Tierfarm" },
                        { "Factory" , "Fabrik" },
                        { "Farm" , "Bauernhof" },
                        { "FarmFields" , "Farm-Felder" },
                        { "Plantation" , "Pflanzung" },
                        { "Resource" , "Ressource" },
                        { "Public" , "Öffentliche Gebäude" },
                        { "PublicBuildings" , "Öffentliche Gebäude" },
                        { "Demand" , "Nachfrage" },
                        { "Marine" , "Marine" },
                        { "Special" , "Spezial" },
                        { "Trade" , "Handel" },
                        { "(1)Ecos" , "(1) Ecos" },
                        { "(2)Tycoons" , "(2) Tycoons" },
                        { "(3)Techs" , "(3) Techniker" },
                        { "Others" , "Andere" },
                        { "Energy" , "Energie" },
                        { "BlackSmokers(DeepSea)" , "Schwarze Raucher (Tiefsee)" },
                        { "BlackSmokers(Normal)" , "Schwarze Raucher (Normal)" },
                        { "(1)Earth" , "(1) Erde" },
                        { "(2)Arctic" , "(2) Arktis" },
                        { "(3)Moon" , "(3) Moon" },
                        { "(4)Tundra" , "(4) Tundra" },
                        { "(5)Orbit" , "(5) Umlaufbahn" },
                        { "Facilities" , "Einrichtungen" },
                        { "Ornaments" , "Ornamente" },
                        { "GlobalModules" , "Globale Module" },
                        { "Laboratories" , "Laboratorien" },
                        { "Modules" , "Module" },
                        { "Agriculture" , "Landwirtschaft" },
                        { "Biotech" , "Biotechnologie" },
                        { "Chemical" , "Chemikalie" },
                        { "Electronics" , "Elektronik" },
                        { "Food" , "Lebensmittel" },
                        { "Heavy" , "Schwer" },
                        { "Mining" , "Bergbau" },
                        { "TundraModules" , "Tundra-Module" },
                        { "IndustryModules" , "Industriemodule" },
                        { "CentralTechUnitReactor" , "Zentraler Tech-Unit-Reaktor" },
                        { "(1)Farmers" , "(1) Landwirte" },
                        { "(2)Workers" , "(2) Arbeitnehmer" },
                        { "(3)Artisans" , "(3) Handwerker" },
                        { "(4)Engineers" , "(4) Ingenieure" },
                        { "(5)Investors" , "(5) Investoren" },
                        { "(6)OldWorldFields" , "(6) Felder der Alten Welt" },
                        { "(7)Jornaleros" , "(7) Jornaleros" },
                        { "(8)Obreros" , "(8) Obreros" },
                        { "(9)NewWorldFields" , "(9) Neue Weltfelder" },
                        { "AllWorlds" , "Alle Welten" },
                        { "Attractiveness" , "Attraktivität" },
                        { "Electricity" , "Elektrizität" },
                        { "FarmBuildings" , "Bauernhofgebäude" },
                        { "ProductionBuildings" , "Produktionsgebäude" },
                        { "Depots" , "Depots" },
                        { "Logistics" , "Logistik" },
                        { "Shipyards" , "Schiffswerften" },
                        { "SpecialBuildings" , "Spezielle Gebäude" },
                        { "MiningBuildings" , "Bergbau Gebäude" },
                        { "OrnamentalBuildings" , "Ornamente" }
                    }
                    },
                {
                    "pol", new Dictionary<string, string>() {
                        { "Military" , "Wojsko" },
                        { "Camps" , "Obozy" },
                        { "Production" , "Produkcja" },
                        { "Ornament" , "Ornamenty" },
                        { "ManorialPalace" , "Pałac Manoriałów" },
                        { "PlayerBuildings" , "Budynki dla graczy" },
                        { "Harbour" , "Port" },
                        { "Harbor" , "Port" },
                        { "Residence" , "Rezydencja" },
                        { "Animalfarm" , "Gospodarstwo hodowlane" },
                        { "Factory" , "Fabryka" },
                        { "Farm" , "Gospodarstwo" },
                        { "FarmFields" , "Pola uprawne" },
                        { "Plantation" , "Plantacja" },
                        { "Resource" , "Zasoby" },
                        { "Public" , "Budynki publiczne" },
                        { "PublicBuildings" , "Budynki publiczne" },
                        { "Demand" , "Popyt" },
                        { "Marine" , "Żegluga morska" },
                        { "Special" , "Specjalne" },
                        { "Trade" , "Handel" },
                        { "(1)Ecos" , "(1) Ecos" },
                        { "(2)Tycoons" , "(2) Potentaci" },
                        { "(3)Techs" , "(3) Techniki" },
                        { "Others" , "Inne" },
                        { "Energy" , "Energia" },
                        { "BlackSmokers(DeepSea)" , "Czarni palacze (Morze Głębokie)" },
                        { "BlackSmokers(Normal)" , "Czarni palacze (normalni)" },
                        { "(1)Earth" , "(1) Ziemia" },
                        { "(2)Arctic" , "(2) Arktyka" },
                        { "(3)Moon" , "(3) Księżyc" },
                        { "(4)Tundra" , "(4) Tundra" },
                        { "(5)Orbit" , "(5) Orbita" },
                        { "Facilities" , "Udogodnienia" },
                        { "Ornaments" , "Ornamenty" },
                        { "GlobalModules" , "Moduły globalne" },
                        { "Laboratories" , "Laboratoria" },
                        { "Modules" , "Moduły" },
                        { "Agriculture" , "Rolnictwo" },
                        { "Biotech" , "Biotechnologia" },
                        { "Chemical" , "Chemikalia" },
                        { "Electronics" , "Elektronika" },
                        { "Food" , "Żywność" },
                        { "Heavy" , "Ciężki" },
                        { "Mining" , "Górnictwo" },
                        { "TundraModules" , "Moduły Tundra" },
                        { "IndustryModules" , "Moduły branżowe" },
                        { "CentralTechUnitReactor" , "Reaktor centralnej jednostki technicznej" },
                        { "(1)Farmers" , "(1) Rolnicy" },
                        { "(2)Workers" , "(2) Pracownicy" },
                        { "(3)Artisans" , "(3) rzemieślnicy" },
                        { "(4)Engineers" , "(4) Inżynierowie" },
                        { "(5)Investors" , "(5) Inwestorzy" },
                        { "(6)OldWorldFields" , "(6) Pola Starego Świata" },
                        { "(7)Jornaleros" , "(7) Jornaleros" },
                        { "(8)Obreros" , "(8) Obreros" },
                        { "(9)NewWorldFields" , "(9) Nowe pola światowe" },
                        { "AllWorlds" , "Wszystkie światy" },
                        { "Attractiveness" , "Atrakcyjność" },
                        { "Electricity" , "Energia elektryczna" },
                        { "FarmBuildings" , "Budynki gospodarcze" },
                        { "ProductionBuildings" , "Budynki produkcyjne" },
                        { "Depots" , "Magazyny" },
                        { "Logistics" , "Logistyka" },
                        { "Shipyards" , "Stocznie" },
                        { "SpecialBuildings" , "Budynki specjalne" },
                        { "MiningBuildings" , "Budynki górnicze" },
                        { "OrnamentalBuildings" , "Ornamenty" }
                    }
                    },
                {
                    "rus", new Dictionary<string, string>() {
                        { "Military" , "Военные" },
                        { "Camps" , "Лагеря" },
                        { "Production" , "Производство" },
                        { "Ornament" , "Орнаменты" },
                        { "ManorialPalace" , "Поместный дворец" },
                        { "PlayerBuildings" , "Здания для игроков" },
                        { "Harbour" , "гавань" },
                        { "Harbor" , "гавань" },
                        { "Residence" , "Резиденция" },
                        { "Animalfarm" , "Анимальфарм" },
                        { "Factory" , "Завод" },
                        { "Farm" , "Ферма" },
                        { "FarmFields" , "Фермерские поля" },
                        { "Plantation" , "Плантация" },
                        { "Resource" , "Ресурс" },
                        { "Public" , "Общественные здания" },
                        { "PublicBuildings" , "Общественные здания" },
                        { "Demand" , "Спрос" },
                        { "Marine" , "Морпех" },
                        { "Special" , "Специально" },
                        { "Trade" , "Торговля" },
                        { "(1)Ecos" , "(1) Экос" },
                        { "(2)Tycoons" , "(2) Талисманы" },
                        { "(3)Techs" , "(3) Техники" },
                        { "Others" , "Другие" },
                        { "Energy" , "Энергетика" },
                        { "BlackSmokers(DeepSea)" , "Чернокожие курильщики (Глубоководье)" },
                        { "BlackSmokers(Normal)" , "Чернокожие курильщики (нормальные)" },
                        { "(1)Earth" , "(1) Земля" },
                        { "(2)Arctic" , "(2) Арктика" },
                        { "(3)Moon" , "(3) Луна" },
                        { "(4)Tundra" , "(4) Тундра" },
                        { "(5)Orbit" , "(5) Орбита" },
                        { "Facilities" , "Объекты" },
                        { "Ornaments" , "Орнаменты" },
                        { "GlobalModules" , "Глобальные модули" },
                        { "Laboratories" , "Лаборатории" },
                        { "Modules" , "Модули" },
                        { "Agriculture" , "Сельское хозяйство" },
                        { "Biotech" , "Биотехника" },
                        { "Chemical" , "Химикаты" },
                        { "Electronics" , "Электроника" },
                        { "Food" , "Продукты" },
                        { "Heavy" , "Тяжелый" },
                        { "Mining" , "Горное дело" },
                        { "TundraModules" , "Модули тундры" },
                        { "IndustryModules" , "Модули промышленности" },
                        { "CentralTechUnitReactor" , "Реактор центрального технологического блока" },
                        { "(1)Farmers" , "(1) Фермеры" },
                        { "(2)Workers" , "(2) Рабочие" },
                        { "(3)Artisans" , "(3) Ремесленники" },
                        { "(4)Engineers" , "(4) Инженеры" },
                        { "(5)Investors" , "(5) Инвесторы" },
                        { "(6)OldWorldFields" , "(6) Поля Старого Света" },
                        { "(7)Jornaleros" , "(7) Хорналерос" },
                        { "(8)Obreros" , "(8) Обрерос" },
                        { "(9)NewWorldFields" , "(9) Новые Поля Мира" },
                        { "AllWorlds" , "Все миры" },
                        { "Attractiveness" , "Привлекательность" },
                        { "Electricity" , "Электричество" },
                        { "FarmBuildings" , "Фермерские здания" },
                        { "ProductionBuildings" , "Производственные здания" },
                        { "Depots" , "Аптеки" },
                        { "Logistics" , "Логистика" },
                        { "Shipyards" , "Судоремонтные заводы" },
                        { "SpecialBuildings" , "Специальные здания" },
                        { "MiningBuildings" , "Горнодобывающие здания" },
                        { "OrnamentalBuildings" , "Орнаменты" }
                    }
                    },
            };
        }

        public static string GetTreeLocalization(string localizationHeader)
        {
            var language = Localization.Localization.GetLanguageCodeFromName(MainWindow.SelectedLanguage);
            try
            {
                if (TreeLocalization.Translations[language][localizationHeader.Replace(" ", String.Empty)] != null)
                {
                    var localization = TreeLocalization.Translations[language][localizationHeader.Replace(" ", String.Empty)];
                    return localization;
                }
                else
                {
                    return localizationHeader;
                }
            }
            catch( Exception ex)
            {
                return localizationHeader;
            }
        }
    }
}