using System.Collections.Generic;
using PresetParser.Models;

namespace PresetParser
{
    public static class ExtraPresets
    {
        public static IEnumerable<ExtraPreset> GetExtraPresets(string annoVersion)
        {
            var result = new List<ExtraPreset>();

            switch (annoVersion)
            {
                case Constants.ANNO_VERSION_1404:
                    result.AddRange(GetExtraPresetsForAnno1404());
                    break;
                case Constants.ANNO_VERSION_2070:
                    result.AddRange(GetExtraPresetsForAnno2070());
                    break;
                case Constants.ANNO_VERSION_1800:
                    result.AddRange(GetExtraPresetsForAnno1800());
                    break;
            }

            return result;
        }

        public static IEnumerable<BlockingTile> GetBlockingTiles()
        {
            var result = new List<BlockingTile>();
            result.Add(new BlockingTile { BuildBlockerX = 1, BuildBlockerZ = 1, Identifier = "BlockTile_1x1", LocaEng = "Block Tile 1x1", LocaGer = "Blockkachel 1x1", LocaFra = "Carrelage en blocs 1x1", LocaPol = "Blok Dachówka 1x1", LocaRus = "Блок Плитка 1x1", LocaEsp = "Baldosa de bloque 1x1" });
            return result;
        }

        public static IEnumerable<ExtraRoads> GetExtraRoads()
        {
            var result = new List<ExtraRoads>();
            result.Add(new ExtraRoads { BuildBlockerX = 1, BuildBlockerZ = 3, Faction = "Roads (x3)", Identifier = "Street_1x3", Guid = 0, LocaEng = "Road 1x 3", LocaGer = "Straßen 1x 3", LocaFra = "Route 1x 3", LocaPol = "Drogowa 1x 3", LocaRus = "Дорога 1x 3", LocaEsp = "Carreteras 1x 3" });
            result.Add(new ExtraRoads { BuildBlockerX = 1, BuildBlockerZ = 6, Faction = "Roads (x3)", Identifier = "Street_1x6", Guid = 0, LocaEng = "Road 1x 6", LocaGer = "Straßen 1x 6", LocaFra = "Route 1x 6", LocaPol = "Drogowa 1x 6", LocaRus = "Дорога 1x 6", LocaEsp = "Carreteras 1x 6" });
            result.Add(new ExtraRoads { BuildBlockerX = 1, BuildBlockerZ = 9, Faction = "Roads (x3)", Identifier = "Street_1x9", Guid = 0, LocaEng = "Road 1x 9", LocaGer = "Straßen 1x 9", LocaFra = "Route 1x 9", LocaPol = "Drogowa 1x 9", LocaRus = "Дорога 1x 9", LocaEsp = "Carreteras 1x 9" });
            result.Add(new ExtraRoads { BuildBlockerX = 1, BuildBlockerZ = 4, Faction = "Roads (x4)", Identifier = "Street_1x4", Guid = 0, LocaEng = "Road 1x 4", LocaGer = "Straßen 1x 4", LocaFra = "Route 1x 4", LocaPol = "Drogowa 1x 4", LocaRus = "Дорога 1x 4", LocaEsp = "Carreteras 1x 4" });
            result.Add(new ExtraRoads { BuildBlockerX = 1, BuildBlockerZ = 8, Faction = "Roads (x4)", Identifier = "Street_1x8", Guid = 0, LocaEng = "Road 1x 8", LocaGer = "Straßen 1x 8", LocaFra = "Route 1x 8", LocaPol = "Drogowa 1x 8", LocaRus = "Дорога 1x 8", LocaEsp = "Carreteras 1x 8" });
            result.Add(new ExtraRoads { BuildBlockerX = 1, BuildBlockerZ = 12, Faction = "Roads (x4)", Identifier = "Street_1x12", Guid = 0, LocaEng = "Road 1x12", LocaGer = "Straßen 1x12", LocaFra = "Route 1x12", LocaPol = "Drogowa 1x12", LocaRus = "Дорога 1x12", LocaEsp = "Carreteras 1x120" });
            result.Add(new ExtraRoads { BuildBlockerX = 1, BuildBlockerZ = 16, Faction = "Roads (x4)", Identifier = "Street_1x16", Guid = 0, LocaEng = "Road 1x16", LocaGer = "Straßen 1x16", LocaFra = "Route 1x16", LocaPol = "Drogowa 1x16", LocaRus = "Дорога 1x16", LocaEsp = "Carreteras 1x16" });
            result.Add(new ExtraRoads { BuildBlockerX = 1, BuildBlockerZ = 5, Faction = "Roads (x5)", Identifier = "Street_1x5", Guid = 0, LocaEng = "Road 1x 5", LocaGer = "Straßen 1x 5", LocaFra = "Route 1x 5", LocaPol = "Drogowa 1x 5", LocaRus = "Дорога 1x 5", LocaEsp = "Carreteras 1x 5" });
            result.Add(new ExtraRoads { BuildBlockerX = 1, BuildBlockerZ = 10, Faction = "Roads (x5)", Identifier = "Street_1x10", Guid = 0, LocaEng = "Road 1x10", LocaGer = "Straßen 1x10", LocaFra = "Route 1x10", LocaPol = "Drogowa 1x10", LocaRus = "Дорога 1x10", LocaEsp = "Carreteras 1x10" });
            result.Add(new ExtraRoads { BuildBlockerX = 1, BuildBlockerZ = 15, Faction = "Roads (x5)", Identifier = "Street_1x15", Guid = 0, LocaEng = "Road 1x15", LocaGer = "Straßen 1x15", LocaFra = "Route 1x15", LocaPol = "Drogowa 1x15", LocaRus = "Дорога 1x15", LocaEsp = "Carreteras 1x15" });
            result.Add(new ExtraRoads { BuildBlockerX = 1, BuildBlockerZ = 20, Faction = "Roads (x5)", Identifier = "Street_1x20", Guid = 0, LocaEng = "Road 1x20", LocaGer = "Straßen 1x20", LocaFra = "Route 1x20", LocaPol = "Drogowa 1x20", LocaRus = "Дорога 1x20", LocaEsp = "Carreteras 1x20" });
            result.Add(new ExtraRoads { BuildBlockerX = 1, BuildBlockerZ = 7, Faction = "Other Roads", Identifier = "Street_1x7", Guid = 0, LocaEng = "Road 1x 7", LocaGer = "Straßen 1x 7", LocaFra = "Route 1x 7", LocaPol = "Drogowa 1x 7", LocaRus = "Дорога 1x 7", LocaEsp = "Carreteras 1x 7" });
            result.Add(new ExtraRoads { BuildBlockerX = 1, BuildBlockerZ = 11, Faction = "Other Roads", Identifier = "Street_1x11", Guid = 0, LocaEng = "Road 1x11", LocaGer = "Straßen 1x11", LocaFra = "Route 1x11", LocaPol = "Drogowa 1x11", LocaRus = "Дорога 1x11", LocaEsp = "Carreteras 1x11" });
            result.Add(new ExtraRoads { BuildBlockerX = 1, BuildBlockerZ = 13, Faction = "Other Roads", Identifier = "Street_1x13", Guid = 0, LocaEng = "Road 1x13", LocaGer = "Straßen 1x13", LocaFra = "Route 1x13", LocaPol = "Drogowa 1x13", LocaRus = "Дорога 1x13", LocaEsp = "Carreteras 1x13" });
            result.Add(new ExtraRoads { BuildBlockerX = 1, BuildBlockerZ = 14, Faction = "Other Roads", Identifier = "Street_1x14", Guid = 0, LocaEng = "Road 1x14", LocaGer = "Straßen 1x14", LocaFra = "Route 1x14", LocaPol = "Drogowa 1x14", LocaRus = "Дорога 1x14", LocaEsp = "Carreteras 1x14" });
            result.Add(new ExtraRoads { BuildBlockerX = 1, BuildBlockerZ = 17, Faction = "Other Roads", Identifier = "Street_1x17", Guid = 0, LocaEng = "Road 1x17", LocaGer = "Straßen 1x17", LocaFra = "Route 1x17", LocaPol = "Drogowa 1x17", LocaRus = "Дорога 1x17", LocaEsp = "Carreteras 1x17" });
            result.Add(new ExtraRoads { BuildBlockerX = 1, BuildBlockerZ = 19, Faction = "Other Roads", Identifier = "Street_1x19", Guid = 0, LocaEng = "Road 1x19", LocaGer = "Straßen 1x19", LocaFra = "Route 1x19", LocaPol = "Drogowa 1x19", LocaRus = "Дорога 1x19", LocaEsp = "Carreteras 1x19" });
            return result;
        }

        private static IEnumerable<ExtraPreset> GetExtraPresetsForAnno1404()
        {
            var result = new List<ExtraPreset>();

            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 2, Faction = "Production", Group = "Farm Fields", Header = "(A4) Anno 1404", IconFileName = "A4_icon_116_22.png", Identifier = "FarmField_3x2", Guid = 0, InfluenceRadius = 0, InfluenceRange = 0, Template = "FarmFields", LocaEng = "(3x2) Farm field", LocaGer = "(3x2) Gemüseäcker", LocaFra = "(3x2) Champ agricole", LocaPol = "(3x2) Pole", LocaRus = "(3x2) Поле", LocaEsp = "(3x2) Campo de cultivo" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Production", Group = "Farm Fields", Header = "(A4) Anno 1404", IconFileName = "A4_icon_116_22.png", Identifier = "FarmField_3x3", Guid = 0, InfluenceRadius = 0, InfluenceRange = 0, Template = "FarmFields", LocaEng = "(3x3) Farm field", LocaGer = "(3x3) Gemüseäcker", LocaFra = "(3x3) Champ agricole", LocaPol = "(3x3) Pole", LocaRus = "(3x3) Поле", LocaEsp = "(3x3) Campo de cultivo" });
            result.Add(new ExtraPreset { BuildBlockerX = 4, BuildBlockerZ = 3, Faction = "Production", Group = "Farm Fields", Header = "(A4) Anno 1404", IconFileName = "A4_icon_116_22.png", Identifier = "FarmField_4x3", Guid = 0, InfluenceRadius = 0, InfluenceRange = 0, Template = "FarmFields", LocaEng = "(4x3) Farm field", LocaGer = "(4x3) Gemüseäcker", LocaFra = "(4x3) Champ agricole", LocaPol = "(4x3) Pole", LocaRus = "(4x3) Поле", LocaEsp = "(4x3) Campo de cultivo" });
            result.Add(new ExtraPreset { BuildBlockerX = 4, BuildBlockerZ = 4, Faction = "Production", Group = "Farm Fields", Header = "(A4) Anno 1404", IconFileName = "A4_icon_116_22.png", Identifier = "FarmField_4x4", Guid = 0, InfluenceRadius = 0, InfluenceRange = 0, Template = "FarmFields", LocaEng = "(4x4) Farm field", LocaGer = "(4x4) Gemüseäcker", LocaFra = "(4x4) Champ agricole", LocaPol = "(4x4) Pole", LocaRus = "(4x4) Поле", LocaEsp = "(4x4) Campo de cultivo" });

            return result;
        }

        private static IEnumerable<ExtraPreset> GetExtraPresetsForAnno2070()
        {
            var result = new List<ExtraPreset>();

            result.Add(new ExtraPreset { BuildBlockerX = 5, BuildBlockerZ = 6, Faction = "Others", Group = "Black Smokers (Deep Sea)", Header = "(A5) Anno 2070", IconFileName = "icon_30_281.png", Identifier = "black_smoker_miner_gold_II", Guid = 0, InfluenceRadius = 0, InfluenceRange = 0, Template = "FarmBuilding", LocaEng = "Gold Metal converter", LocaGer = "Metallkonverter Gold", LocaFra = "L'or Convertisseur métallique", LocaPol = "Konwerter warstw złotonośnych", LocaRus = "Конвертер золота", LocaEsp = "Convertidor de metal dorado" });
            result.Add(new ExtraPreset { BuildBlockerX = 5, BuildBlockerZ = 6, Faction = "Others", Group = "Black Smokers (Deep Sea)", Header = "(A5) Anno 2070", IconFileName = "icon_30_282.png", Identifier = "black_smoker_miner_copper_II", Guid = 0, InfluenceRadius = 0, InfluenceRange = 0, Template = "FarmBuilding", LocaEng = "Copper Metal converter", LocaGer = "Metallkonverter Kupfer", LocaFra = "Copère Convertisseur métallique", LocaPol = "Konwerter warstw miedzionośnych", LocaRus = "Конвертер меди", LocaEsp = "Convertidor de cobre y metal" });
            result.Add(new ExtraPreset { BuildBlockerX = 5, BuildBlockerZ = 6, Faction = "Others", Group = "Black Smokers (Deep Sea)", Header = "(A5) Anno 2070", IconFileName = "icon_30_283.png", Identifier = "black_smoker_miner_uranium_II", Guid = 0, InfluenceRadius = 0, InfluenceRange = 0, Template = "FarmBuilding", LocaEng = "Uranium Metal converter", LocaGer = "Metallkonverter Uran", LocaFra = "L'uranium Convertisseur métallique", LocaPol = "Konwerter warstw bogatych w uran", LocaRus = "Конвертер урана", LocaEsp = "Convertidor de uranio metálico" });
            result.Add(new ExtraPreset { BuildBlockerX = 5, BuildBlockerZ = 6, Faction = "Others", Group = "Black Smokers (Deep Sea)", Header = "(A5) Anno 2070", IconFileName = "icon_30_280.png", Identifier = "black_smoker_miner_iron_II", Guid = 0, InfluenceRadius = 0, InfluenceRange = 0, Template = "FarmBuilding", LocaEng = "Iron Metal converter", LocaGer = "Metallkonverter Eisen", LocaFra = "Fer Convertisseur métallique", LocaPol = "Konwerter żelaza", LocaRus = "Конвертер железа", LocaEsp = "Hierro Convertidor de metales" });
            result.Add(new ExtraPreset { BuildBlockerX = 4, BuildBlockerZ = 4, Faction = "Others", Group = "Public", Header = "(A5) Anno 2070", IconFileName = "icon_27_10.png", Identifier = "markethouse", Guid = 0, InfluenceRadius = 20, InfluenceRange = 0, Template = "Markethouse", LocaEng = "Depot", LocaGer = "Warendepot", LocaFra = "Dépôt", LocaPol = "Skład", LocaRus = "Хранилище", LocaEsp = "Depósito" });

            return result;
        }

        private static IEnumerable<ExtraPreset> GetExtraPresetsForAnno1800()
        {
            var result = new List<ExtraPreset>();

            result.Add(new ExtraPreset { BuildBlockerX = 5, BuildBlockerZ = 5, Faction = "(02) Workers", Group = null, Header = "(A7) Anno 1800", IconFileName = "A7_warehouse.png", Identifier = "Logistic_02 (Warehouse I)", Guid = 1010371, InfluenceRadius = 0, InfluenceRange = 0, Template = "Warehouse", LocaEng = "Small Warehouse", LocaGer = "Lagerhaus", LocaFra = "Petit entrepôt", LocaPol = "Mały magazyn", LocaRus = "Маленький склад", LocaEsp = "Pequeño almacén" });
            result.Add(new ExtraPreset { BuildBlockerX = 5, BuildBlockerZ = 5, Faction = "(03) Artisans", Group = null, Header = "(A7) Anno 1800", IconFileName = "A7_warehouse.png", Identifier = "Logistic_02 (Warehouse I)", Guid = 1010371, InfluenceRadius = 0, InfluenceRange = 0, Template = "Warehouse", LocaEng = "Small Warehouse", LocaGer = "Lagerhaus", LocaFra = "Petit entrepôt", LocaPol = "Mały magazyn", LocaRus = "Маленький склад", LocaEsp = "Pequeño almacén" });
            result.Add(new ExtraPreset { BuildBlockerX = 5, BuildBlockerZ = 5, Faction = "(04) Engineers", Group = null, Header = "(A7) Anno 1800", IconFileName = "A7_warehouse.png", Identifier = "Logistic_02 (Warehouse I)", Guid = 1010371, InfluenceRadius = 0, InfluenceRange = 0, Template = "Warehouse", LocaEng = "Small Warehouse", LocaGer = "Lagerhaus", LocaFra = "Petit entrepôt", LocaPol = "Mały magazyn", LocaRus = "Маленький склад", LocaEsp = "Pequeño almacén" });
            result.Add(new ExtraPreset { BuildBlockerX = 5, BuildBlockerZ = 5, Faction = "(05) Investors", Group = null, Header = "(A7) Anno 1800", IconFileName = "A7_warehouse.png", Identifier = "Logistic_02 (Warehouse I)", Guid = 1010371, InfluenceRadius = 0, InfluenceRange = 0, Template = "Warehouse", LocaEng = "Small Warehouse", LocaGer = "Lagerhaus", LocaFra = "Petit entrepôt", LocaPol = "Mały magazyn", LocaRus = "Маленький склад", LocaEsp = "Pequeño almacén" });
            result.Add(new ExtraPreset { BuildBlockerX = 5, BuildBlockerZ = 5, Faction = "(07) Jornaleros", Group = null, Header = "(A7) Anno 1800", IconFileName = "A7_warehouse.png", Identifier = "Logistic_02 (Warehouse I)", Guid = 1010371, InfluenceRadius = 0, InfluenceRange = 0, Template = "Warehouse", LocaEng = "Small Warehouse", LocaGer = "Lagerhaus", LocaFra = "Petit entrepôt", LocaPol = "Mały magazyn", LocaRus = "Маленький склад", LocaEsp = "Pequeño almacén" });
            result.Add(new ExtraPreset { BuildBlockerX = 5, BuildBlockerZ = 5, Faction = "(08) Obreros", Group = null, Header = "(A7) Anno 1800", IconFileName = "A7_warehouse.png", Identifier = "Logistic_02 (Warehouse I)", Guid = 1010371, InfluenceRadius = 0, InfluenceRange = 0, Template = "Warehouse", LocaEng = "Small Warehouse", LocaGer = "Lagerhaus", LocaFra = "Petit entrepôt", LocaPol = "Mały magazyn", LocaRus = "Маленький склад", LocaEsp = "Pequeño almacén" });
            result.Add(new ExtraPreset { BuildBlockerX = 5, BuildBlockerZ = 5, Faction = "(10) Explorers", Group = null, Header = "(A7) Anno 1800", IconFileName = "A7_warehouse.png", Identifier = "Logistic_02 (Warehouse I)", Guid = 1010371, InfluenceRadius = 0, InfluenceRange = 0, Template = "Warehouse", LocaEng = "Small Warehouse", LocaGer = "Lagerhaus", LocaFra = "Petit entrepôt", LocaPol = "Mały magazyn", LocaRus = "Маленький склад", LocaEsp = "Pequeño almacén" });
            result.Add(new ExtraPreset { BuildBlockerX = 5, BuildBlockerZ = 5, Faction = "(11) Technicians", Group = null, Header = "(A7) Anno 1800", IconFileName = "A7_warehouse.png", Identifier = "Logistic_02 (Warehouse I)", Guid = 1010371, InfluenceRadius = 0, InfluenceRange = 0, Template = "Warehouse", LocaEng = "Small Warehouse", LocaGer = "Lagerhaus", LocaFra = "Petit entrepôt", LocaPol = "Mały magazyn", LocaRus = "Маленький склад", LocaEsp = "Pequeño almacén" });
            result.Add(new ExtraPreset { BuildBlockerX = 5, BuildBlockerZ = 5, Faction = "(13) Scholars", Group = null, Header = "(A7) Anno 1800", IconFileName = "A7_warehouse.png", Identifier = "Logistic_02 (Warehouse I)", Guid = 1010371, InfluenceRadius = 0, InfluenceRange = 0, Template = "Warehouse", LocaEng = "Small Warehouse", LocaGer = "Lagerhaus", LocaFra = "Petit entrepôt", LocaPol = "Mały magazyn", LocaRus = "Маленький склад", LocaEsp = "Pequeño almacén" });
            result.Add(new ExtraPreset { BuildBlockerX = 5, BuildBlockerZ = 5, Faction = "(14) Shepherds", Group = null, Header = "(A7) Anno 1800", IconFileName = "A7_warehouse.png", Identifier = "Logistic_02 (Warehouse I)", Guid = 1010371, InfluenceRadius = 0, InfluenceRange = 0, Template = "Warehouse", LocaEng = "Small Warehouse", LocaGer = "Lagerhaus", LocaFra = "Petit entrepôt", LocaPol = "Mały magazyn", LocaRus = "Маленький склад", LocaEsp = "Pequeño almacén" });
            result.Add(new ExtraPreset { BuildBlockerX = 5, BuildBlockerZ = 5, Faction = "(15) Elders", Group = null, Header = "(A7) Anno 1800", IconFileName = "A7_warehouse.png", Identifier = "Logistic_02 (Warehouse I)", Guid = 1010371, InfluenceRadius = 0, InfluenceRange = 0, Template = "Warehouse", LocaEng = "Small Warehouse", LocaGer = "Lagerhaus", LocaFra = "Petit entrepôt", LocaPol = "Mały magazyn", LocaRus = "Маленький склад", LocaEsp = "Pequeño almacén" });
            result.Add(new ExtraPreset { BuildBlockerX = 6, BuildBlockerZ = 4, Faction = "Attractiveness", Group = "Modules", Header = "(A7) Anno 1800", IconFileName = "A7_Zoo module.png", Identifier = "Culture_01_module", Guid = 100455, InfluenceRadius = 0, InfluenceRange = 0, Template = "CultureModule", LocaEng = "Zoo Module (6x4)", LocaGer = "Zoo-Modul (6x4)", LocaFra = "Module du zoo (6x4)", LocaPol = "Moduł ZOO (6x4)", LocaRus = "Модуль зоопарка (6x4)", LocaEsp = "Módulo Zoo (6x4)" });
            result.Add(new ExtraPreset { BuildBlockerX = 5, BuildBlockerZ = 4, Faction = "Attractiveness", Group = "Modules", Header = "(A7) Anno 1800", IconFileName = "A7_Museum module.png", Identifier = "Culture_02_module", Guid = 100454, InfluenceRadius = 0, InfluenceRange = 0, Template = "CultureModule", LocaEng = "Museum Module (5x4)", LocaGer = "Museumsmodul (5x4)", LocaFra = "Module du musée (5x4)", LocaPol = "Moduł Muzeum (5x4)", LocaRus = "Модуль музея (5x4)", LocaEsp = "Módulo Museo (5x4)" });
            result.Add(new ExtraPreset { BuildBlockerX = 5, BuildBlockerZ = 4, Faction = "Attractiveness", Group = "Modules", Header = "(A7) Anno 1800", IconFileName = "A7_botanic_module.png", Identifier = "Culture_03_module", Guid = 111104, InfluenceRadius = 0, InfluenceRange = 0, Template = "CultureModule", LocaEng = "Botanica Module (5x4)", LocaGer = "Botanikmodul (5x4)", LocaFra = "Module Botanica (5x4)", LocaPol = "Moduł botaniczny (5x4)", LocaRus = "модуль Ботанический (5x4)", LocaEsp = "Módulo Botanica (5x4)" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "(04) Engineers", Group = "Skyscraper", Header = "(A7) Anno 1800", IconFileName = "A7_dlc_high_life_256.png", Identifier = "A7_residence_SkyScraper_4lvl1", Guid = 601888, InfluenceRadius = 4, InfluenceRange = 0, Template = "SkyScraper_Residence", LocaEng = "Skyscraper (T4 I)", LocaGer = "Wolkenkratzer (T4 I)", LocaFra = "Gratte-ciel (T4 I)", LocaPol = "Wieżowiec (T4 I)", LocaRus = "Небоскребы (T4 I)", LocaEsp = "Rascacielos (T4 I)" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "(04) Engineers", Group = "Skyscraper", Header = "(A7) Anno 1800", IconFileName = "A7_dlc_high_life_256.png", Identifier = "A7_residence_SkyScraper_4lvl2", Guid = 601889, InfluenceRadius = 4.25, InfluenceRange = 0, Template = "SkyScraper_Residence", LocaEng = "Skyscraper (T4 II)", LocaGer = "Wolkenkratzer (T4 II)", LocaFra = "Gratte-ciel (T4 II)", LocaPol = "Wieżowiec (T4 II)", LocaRus = "Небоскребы (T4 II)", LocaEsp = "Rascacielos (T4 II)" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "(04) Engineers", Group = "Skyscraper", Header = "(A7) Anno 1800", IconFileName = "A7_dlc_high_life_256.png", Identifier = "A7_residence_SkyScraper_4lvl3", Guid = 601890, InfluenceRadius = 5, InfluenceRange = 0, Template = "SkyScraper_Residence", LocaEng = "Skyscraper (T4 III)", LocaGer = "Wolkenkratzer (T4 III)", LocaFra = "Gratte-ciel (T4 III)", LocaPol = "Wieżowiec (T4 III)", LocaRus = "Небоскребы (T4 III)", LocaEsp = "Rascacielos (T4 III)" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "(05) Investors", Group = "Skyscraper", Header = "(A7) Anno 1800", IconFileName = "A7_dlc_high_life_256.png", Identifier = "A7_residence_SkyScraper_5lvl1", Guid = 601882, InfluenceRadius = 4, InfluenceRange = 0, Template = "SkyScraper_Residence", LocaEng = "Skyscraper (T5 I)", LocaGer = "Wolkenkratzer (T5 I)", LocaFra = "Gratte-ciel (T5 I)", LocaPol = "Wieżowiec ((T5 I)", LocaRus = "Небоскребы (T5 I)", LocaEsp = "Rascacielos (T5 I)" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "(05) Investors", Group = "Skyscraper", Header = "(A7) Anno 1800", IconFileName = "A7_dlc_high_life_256.png", Identifier = "A7_residence_SkyScraper_5lvl2", Guid = 601883, InfluenceRadius = 4.25, InfluenceRange = 0, Template = "SkyScraper_Residence", LocaEng = "Skyscraper (T5 II)", LocaGer = "Wolkenkratzer (T5 II)", LocaFra = "Gratte-ciel (T5 II)", LocaPol = "Wieżowiec (T5 II)", LocaRus = "Небоскребы (T5 II)", LocaEsp = "Rascacielos (T5 II)" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "(05) Investors", Group = "Skyscraper", Header = "(A7) Anno 1800", IconFileName = "A7_dlc_high_life_256.png", Identifier = "A7_residence_SkyScraper_5lvl3", Guid = 601884, InfluenceRadius = 5, InfluenceRange = 0, Template = "SkyScraper_Residence", LocaEng = "Skyscraper (T5 III)", LocaGer = "Wolkenkratzer (T5 III)", LocaFra = "Gratte-ciel (T5 III)", LocaPol = "Wieżowiec (T5 III)", LocaRus = "Небоскребы (T5 III)", LocaEsp = "Rascacielos (T5 III)" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "(05) Investors", Group = "Skyscraper", Header = "(A7) Anno 1800", IconFileName = "A7_dlc_high_life_256.png", Identifier = "A7_residence_SkyScraper_5lvl4", Guid = 601886, InfluenceRadius = 6, InfluenceRange = 0, Template = "SkyScraper_Residence", LocaEng = "Skyscraper (T5 IV)", LocaGer = "Wolkenkratzer (T5 IV)", LocaFra = "Gratte-ciel (T5 IV)", LocaPol = "Wieżowiec (T5 IV)", LocaRus = "Небоскребы (T5 IV)", LocaEsp = "Rascacielos (T5 IV)" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "(05) Investors", Group = "Skyscraper", Header = "(A7) Anno 1800", IconFileName = "A7_dlc_high_life_256.png", Identifier = "A7_residence_SkyScraper_5lvl5", Guid = 601891, InfluenceRadius = 6.75, InfluenceRange = 0, Template = "SkyScraper_Residence", LocaEng = "Skyscraper (T5 V)", LocaGer = "Wolkenkratzer (T5 V)", LocaFra = "Gratte-ciel (T5 V)", LocaPol = "Wieżowiec (T5 V)", LocaRus = "Небоскребы (T5 V)", LocaEsp = "Rascacielos (T5 V)" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 4, Faction = "(10) Explorers", Group = "Public Buildings", Header = "(A7) Anno 1800", IconFileName = "A7_heating_center.png", Identifier = "Heater_Arctic", Guid = 114751, InfluenceRadius = 0, InfluenceRange = 21, Template = "Heater_Arctic", LocaEng = "Heater", LocaGer = "Heizgerät", LocaFra = "Chaufferie", LocaPol = "Kotłownia", LocaRus = "Подогреватель", LocaEsp = "Calentador" });
            result.Add(new ExtraPreset { BuildBlockerX = 1, BuildBlockerZ = 1, Faction = "Ornaments", Group = "25 Pedestrian Zone", Header = "(A7) Anno 1800", IconFileName = "A7_enclosed_greenery.png", Identifier = "PedestrianZone EnclosedGreenery", Guid = 0, InfluenceRadius = 0, InfluenceRange = 0, Template = "OrnamentalBuilding", LocaEng = "Enclosed Greenery", LocaGer = "Umzäunte Begrünung", LocaFra = "Plantes de trottoir", LocaPol = "Odgrodzona zieleń", LocaRus = "Зеленые насаждения", LocaEsp = "Jardín cercado" });
            result.Add(new ExtraPreset { BuildBlockerX = 1, BuildBlockerZ = 1, Faction = "Ornaments", Group = "25 Pedestrian Zone", Header = "(A7) Anno 1800", IconFileName = "A7_canals.png", Identifier = "PedestrianZone Canal", Guid = 0, InfluenceRadius = 0, InfluenceRange = 0, Template = "OrnamentalBuilding", LocaEng = "Canals", LocaGer = "Kanäle", LocaFra = "Canaux", LocaPol = "Kanały", LocaRus = "Каналы", LocaEsp = "Canales" });
            result.Add(new ExtraPreset { BuildBlockerX = 1, BuildBlockerZ = 1, Faction = "Ornaments", Group = "25 Pedestrian Zone", Header = "(A7) Anno 1800", IconFileName = "A7_sewers.png", Identifier = "PedestrianZone Sewer", Guid = 0, InfluenceRadius = 0, InfluenceRange = 0, Template = "OrnamentalBuilding", LocaEng = "Sewers", LocaGer = "Kanalisation", LocaFra = "Égouts", LocaPol = "Kanały ściekowe", LocaRus = "Канализация", LocaEsp = "Alcantarillas" });
            result.Add(new ExtraPreset { BuildBlockerX = 1, BuildBlockerZ = 1, Faction = "(15) Elders", Group = null, Header = "(A7) Anno 1800", IconFileName = null, Identifier = "WaterCanal", Guid = 0, InfluenceRadius = 0, InfluenceRange = 0, Template = "WaterCanal", LocaEng = "Irrigation Canal", LocaGer = "Bewässerungskanal", LocaFra = "Canal d'irrigation", LocaPol = "Kanał Irygacyjny", LocaRus = "Ирригационный канал", LocaEsp = "Canal de riego" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 4, Faction = "(30) Scenario 1: Eden Burning", Group = "Farm Fields", Header = "(A7) Anno 1800", IconFileName = "A7_fish_pond_module.png", Identifier = "Agriculture_08_field (Fish pool)", Guid = 1010277, InfluenceRadius = 0, InfluenceRange = 0, Template = "Scenario1", LocaEng = "Fish Pool - (5)", LocaGer = "Fischbecken - (5)", LocaFra = "Bassin piscicole - (5)", LocaPol = "Staw rybny - (5)", LocaRus = "Пруд для рыбы - (5)", LocaEsp = "Piscina de peces - (5)" });
            //Extra Menu's for Residences, will not be showed in Preset Tree, and is for now only available for DuxVitae's Tool,
            // but will on later presets VERSION also available for Users, if i made the solution for it.
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColDef)", Group = "(1) Old World", Header = "(A7) Anno 1800", IconFileName = "A7_resident.png", Identifier = "Residence_Old_World", Guid = 1010343, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColDef", LocaEng = "(1) Farmer Residence", LocaGer = "(1) Bauernhaus", LocaFra = "(1) Résidence de fermier", LocaPol = "(1) Dom farmerów", LocaRus = "(1) Жилье фермеров", LocaEsp = "(1) Residencia de granjeros" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColDef)", Group = "(1) Old World", Header = "(A7) Anno 1800", IconFileName = "A7_resident.png", Identifier = "Residence_tier02", Guid = 1010344, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColDef", LocaEng = "(2) Worker Residence", LocaGer = "(2) Arbeiterhaus", LocaFra = "(2) Résidence d'ouvrier", LocaPol = "(2) Dom robotników", LocaRus = "(2) Жилье рабочих", LocaEsp = "(2) Residencia de trabajadores" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColDef)", Group = "(1) Old World", Header = "(A7) Anno 1800", IconFileName = "A7_resident.png", Identifier = "Residence_tier03", Guid = 1010345, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColDef", LocaEng = "(3) Artisan Residence", LocaGer = "(3) Handwerkerhaus", LocaFra = "(3) Résidence d'artisan", LocaPol = "(3) Dom rzemieślników", LocaRus = "(3) Жилье ремесленников", LocaEsp = "(3) Residencia de artesanos" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColDef)", Group = "(1) Old World", Header = "(A7) Anno 1800", IconFileName = "A7_resident.png", Identifier = "Residence_tier04", Guid = 1010346, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColDef", LocaEng = "(4) Engineer Residence", LocaGer = "(4) Ingenieurshaus", LocaFra = "(4) Résidence d'ingénieur", LocaPol = "(4) Dom inżynierów", LocaRus = "(4) Жилье инженеров", LocaEsp = "(4) Residencia de ingenieros" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColDef)", Group = "(1) Old World", Header = "(A7) Anno 1800", IconFileName = "A7_resident.png", Identifier = "Residence_tier05", Guid = 1010347, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColDef", LocaEng = "(5) Investor Residence", LocaGer = "(5) Investorenhaus", LocaFra = "(5) Résidence d'investisseur", LocaPol = "(5) Dom inwestorów", LocaRus = "(5) Жилье инвесторов", LocaEsp = "(5) Residencia de inversores" });
            result.Add(new ExtraPreset { BuildBlockerX = 4, BuildBlockerZ = 4, Faction = "Residences (RoofColDef)", Group = "(1) Old World", Header = "(A7) Anno 1800", IconFileName = "A7_residence_scholars.png", Identifier = "Residence_tier05b", Guid = 114445, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColDef", LocaEng = "(6) Scholar Residence", LocaGer = "(6) Gelehrtenhaus", LocaFra = "(6) Résidence d'Érudit", LocaPol = "(6) Dom uczonego", LocaRus = "(6) Жилье ученого", LocaEsp = "(6) Residencia de eruditos" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColDef)", Group = "(2) New World", Header = "(A7) Anno 1800", IconFileName = "A7_resident.png", Identifier = "Residence_New_World", Guid = 101254, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColDef", LocaEng = "(1) Jornalero Residence", LocaGer = "(1) Jornalero-​Haus", LocaFra = "(1) Résidence de jornalero", LocaPol = "(1) Dom jornaleros", LocaRus = "(1) Жилье хорналеро", LocaEsp = "(1) Residencia de Jornalero" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColDef)", Group = "(2) New World", Header = "(A7) Anno 1800", IconFileName = "A7_resident.png", Identifier = "Residence_colony01_tier02", Guid = 101255, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColDef", LocaEng = "(2) Obrero Residence", LocaGer = "(2) Obrero-​Haus", LocaFra = "(2) Résidence d'obrero", LocaPol = "(2) Dom obreros", LocaRus = "(2) Жилье обреро", LocaEsp = "(2) Residencia de Obrero" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColDef)", Group = "(3) Arctic", Header = "(A7) Anno 1800", IconFileName = "A7_resident.png", Identifier = "Residence_Arctic_World", Guid = 112091, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColDef", LocaEng = "(1) Explorer Shelter", LocaGer = "(1) Entdecker-​Behausung", LocaFra = "(1) Abri d'exploratrice", LocaPol = "(1) Schronienie odkrywców", LocaRus = "(1) Жилище исследователей", LocaEsp = "(1) Refugio de exploradores" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColDef)", Group = "(3) Arctic", Header = "(A7) Anno 1800", IconFileName = "A7_resident.png", Identifier = "Residence_arctic_tier02", Guid = 112652, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColDef", LocaEng = "(2) Technician Shelter", LocaGer = "(2) Techniker-​Behausung", LocaFra = "(2) Abri de technicien", LocaPol = "(2) Schronienie techników", LocaRus = "(2) Жилище техников", LocaEsp = "(2) Refugio de técnico" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColDef)", Group = "(4) Enbesa", Header = "(A7) Anno 1800", IconFileName = "A7_resident.png", Identifier = "Residence_Africa_World", Guid = 114436, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColDef", LocaEng = "(1) Shepherd Residence", LocaGer = "(1) Hirtenhaus", LocaFra = "(1) Résidence de Berger", LocaPol = "(1) Dom pasterzy", LocaRus = "(1) Жилье пастухов", LocaEsp = "(1) Residencia de pastores" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColDef)", Group = "(4) Enbesa", Header = "(A7) Anno 1800", IconFileName = "A7_resident.png", Identifier = "Residence_colony02_tier02", Guid = 114437, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColDef", LocaEng = "(2) Elder Residence", LocaGer = "(2) Ältestenhaus", LocaFra = "(2) Résidence d'Ancien", LocaPol = "(2) Dom starszych", LocaRus = "(2) Жилье старейшин", LocaEsp = "(2) Residencia de ancianas" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (DefColFace)", Group = "(1) Old World", Header = "(A7) Anno 1800", IconFileName = "A7_resident_farmer.png", Identifier = "Residence_Old_World", Guid = 1010343, InfluenceRadius = 0, InfluenceRange = 0, Template = "DefColFace", LocaEng = "(1) Farmer Residence", LocaGer = "(1) Bauernhaus", LocaFra = "(1) Résidence de fermier", LocaPol = "(1) Dom farmerów", LocaRus = "(1) Жилье фермеров", LocaEsp = "(1) Residencia de granjeros" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (DefColFace)", Group = "(1) Old World", Header = "(A7) Anno 1800", IconFileName = "A7_resident_worker.png", Identifier = "Residence_tier02", Guid = 1010344, InfluenceRadius = 0, InfluenceRange = 0, Template = "DefColFace", LocaEng = "(2) Worker Residence", LocaGer = "(2) Arbeiterhaus", LocaFra = "(2) Résidence d'ouvrier", LocaPol = "(2) Dom robotników", LocaRus = "(2) Жилье рабочих", LocaEsp = "(2) Residencia de trabajadores" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (DefColFace)", Group = "(1) Old World", Header = "(A7) Anno 1800", IconFileName = "A7_resident_artisan.png", Identifier = "Residence_tier03", Guid = 1010345, InfluenceRadius = 0, InfluenceRange = 0, Template = "DefColFace", LocaEng = "(3) Artisan Residence", LocaGer = "(3) Handwerkerhaus", LocaFra = "(3) Résidence d'artisan", LocaPol = "(3) Dom rzemieślników", LocaRus = "(3) Жилье ремесленников", LocaEsp = "(3) Residencia de artesanos" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (DefColFace)", Group = "(1) Old World", Header = "(A7) Anno 1800", IconFileName = "A7_resident_engineer.png", Identifier = "Residence_tier04", Guid = 1010346, InfluenceRadius = 0, InfluenceRange = 0, Template = "DefColFace", LocaEng = "(4) Engineer Residence", LocaGer = "(4) Ingenieurshaus", LocaFra = "(4) Résidence d'ingénieur", LocaPol = "(4) Dom inżynierów", LocaRus = "(4) Жилье инженеров", LocaEsp = "(4) Residencia de ingenieros" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (DefColFace)", Group = "(1) Old World", Header = "(A7) Anno 1800", IconFileName = "A7_resident_investor.png", Identifier = "Residence_tier05", Guid = 1010347, InfluenceRadius = 0, InfluenceRange = 0, Template = "DefColFace", LocaEng = "(5) Investor Residence", LocaGer = "(5) Investorenhaus", LocaFra = "(5) Résidence d'investisseur", LocaPol = "(5) Dom inwestorów", LocaRus = "(5) Жилье инвесторов", LocaEsp = "(5) Residencia de inversores" });
            result.Add(new ExtraPreset { BuildBlockerX = 4, BuildBlockerZ = 4, Faction = "Residences (DefColFace)", Group = "(1) Old World", Header = "(A7) Anno 1800", IconFileName = "A7_resident_scholars.png", Identifier = "Residence_tier05b", Guid = 114445, InfluenceRadius = 0, InfluenceRange = 0, Template = "DefColFace", LocaEng = "(6) Scholar Residence", LocaGer = "(6) Gelehrtenhaus", LocaFra = "(6) Résidence d'Érudit", LocaPol = "(6) Dom uczonego", LocaRus = "(6) Жилье ученого", LocaEsp = "(6) Residencia de eruditos" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (DefColFace)", Group = "(2) New World", Header = "(A7) Anno 1800", IconFileName = "A7_resident_jornaleros_0.png", Identifier = "Residence_New_World", Guid = 101254, InfluenceRadius = 0, InfluenceRange = 0, Template = "DefColFace", LocaEng = "(1) Jornalero Residence", LocaGer = "(1) Jornalero-​Haus", LocaFra = "(1) Résidence de jornalero", LocaPol = "(1) Dom jornaleros", LocaRus = "(1) Жилье хорналеро", LocaEsp = "(1) Residencia de Jornalero" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (DefColFace)", Group = "(2) New World", Header = "(A7) Anno 1800", IconFileName = "A7_resident_obrera.png", Identifier = "Residence_colony01_tier02", Guid = 101255, InfluenceRadius = 0, InfluenceRange = 0, Template = "DefColFace", LocaEng = "(2) Obrero Residence", LocaGer = "(2) Obrero-​Haus", LocaFra = "(2) Résidence d'obrero", LocaPol = "(2) Dom obreros", LocaRus = "(2) Жилье обреро", LocaEsp = "(2) Residencia de Obrero" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (DefColFace)", Group = "(3) Arctic", Header = "(A7) Anno 1800", IconFileName = "A7_resident_Explorers.png", Identifier = "Residence_Arctic_World", Guid = 112091, InfluenceRadius = 0, InfluenceRange = 0, Template = "DefColFace", LocaEng = "(1) Explorer Shelter", LocaGer = "(1) Entdecker-​Behausung", LocaFra = "(1) Abri d'exploratrice", LocaPol = "(1) Schronienie odkrywców", LocaRus = "(1) Жилище исследователей", LocaEsp = "(1) Refugio de exploradores" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (DefColFace)", Group = "(3) Arctic", Header = "(A7) Anno 1800", IconFileName = "A7_resident_Technicians.png", Identifier = "Residence_arctic_tier02", Guid = 112652, InfluenceRadius = 0, InfluenceRange = 0, Template = "DefColFace", LocaEng = "(2) Technician Shelter", LocaGer = "(2) Techniker-​Behausung", LocaFra = "(2) Abri de technicien", LocaPol = "(2) Schronienie techników", LocaRus = "(2) Жилище техников", LocaEsp = "(2) Refugio de técnico" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (DefColFace)", Group = "(4) Enbesa", Header = "(A7) Anno 1800", IconFileName = "A7_resident_sheperd.png", Identifier = "Residence_Africa_World", Guid = 114436, InfluenceRadius = 0, InfluenceRange = 0, Template = "DefColFace", LocaEng = "(1) Shepherd Residence", LocaGer = "(1) Hirtenhaus", LocaFra = "(1) Résidence de Berger", LocaPol = "(1) Dom pasterzy", LocaRus = "(1) Жилье пастухов", LocaEsp = "(1) Residencia de pastores" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (DefColFace)", Group = "(4) Enbesa", Header = "(A7) Anno 1800", IconFileName = "A7_resident_elder.png", Identifier = "Residence_colony02_tier02", Guid = 114437, InfluenceRadius = 0, InfluenceRange = 0, Template = "DefColFace", LocaEng = "(2) Elder Residence", LocaGer = "(2) Ältestenhaus", LocaFra = "(2) Résidence d'Ancien", LocaPol = "(2) Dom starszych", LocaRus = "(2) Жилье старейшин", LocaEsp = "(2) Residencia de ancianas" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColFace)", Group = "(1) Old World", Header = "(A7) Anno 1800", IconFileName = "A7_resident_farmer.png", Identifier = "Residence_Old_World", Guid = 1010343, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColFace", LocaEng = "(1) Farmer Residence", LocaGer = "(1) Bauernhaus", LocaFra = "(1) Résidence de fermier", LocaPol = "(1) Dom farmerów", LocaRus = "(1) Жилье фермеров", LocaEsp = "(1) Residencia de granjeros" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColFace)", Group = "(1) Old World", Header = "(A7) Anno 1800", IconFileName = "A7_resident_worker.png", Identifier = "Residence_tier02", Guid = 1010344, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColFace", LocaEng = "(2) Worker Residence", LocaGer = "(2) Arbeiterhaus", LocaFra = "(2) Résidence d'ouvrier", LocaPol = "(2) Dom robotników", LocaRus = "(2) Жилье рабочих", LocaEsp = "(2) Residencia de trabajadores" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColFace)", Group = "(1) Old World", Header = "(A7) Anno 1800", IconFileName = "A7_resident_artisan.png", Identifier = "Residence_tier03", Guid = 1010345, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColFace", LocaEng = "(3) Artisan Residence", LocaGer = "(3) Handwerkerhaus", LocaFra = "(3) Résidence d'artisan", LocaPol = "(3) Dom rzemieślników", LocaRus = "(3) Жилье ремесленников", LocaEsp = "(3) Residencia de artesanos" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColFace)", Group = "(1) Old World", Header = "(A7) Anno 1800", IconFileName = "A7_resident_engineer.png", Identifier = "Residence_tier04", Guid = 1010346, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColFace", LocaEng = "(4) Engineer Residence", LocaGer = "(4) Ingenieurshaus", LocaFra = "(4) Résidence d'ingénieur", LocaPol = "(4) Dom inżynierów", LocaRus = "(4) Жилье инженеров", LocaEsp = "(4) Residencia de ingenieros" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColFace)", Group = "(1) Old World", Header = "(A7) Anno 1800", IconFileName = "A7_resident_investor.png", Identifier = "Residence_tier05", Guid = 1010347, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColFace", LocaEng = "(5) Investor Residence", LocaGer = "(5) Investorenhaus", LocaFra = "(5) Résidence d'investisseur", LocaPol = "(5) Dom inwestorów", LocaRus = "(5) Жилье инвесторов", LocaEsp = "(5) Residencia de inversores" });
            result.Add(new ExtraPreset { BuildBlockerX = 4, BuildBlockerZ = 4, Faction = "Residences (RoofColFace)", Group = "(1) Old World", Header = "(A7) Anno 1800", IconFileName = "A7_resident_scholars.png", Identifier = "Residence_tier05b", Guid = 114445, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColFace", LocaEng = "(6) Scholar Residence", LocaGer = "(6) Gelehrtenhaus", LocaFra = "(6) Résidence d'Érudit", LocaPol = "(6) Dom uczonego", LocaRus = "(6) Жилье ученого", LocaEsp = "(6) Residencia de eruditos" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColFace)", Group = "(2) New World", Header = "(A7) Anno 1800", IconFileName = "A7_resident_jornaleros_0.png", Identifier = "Residence_New_World", Guid = 101254, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColFace", LocaEng = "(1) Jornalero Residence", LocaGer = "(1) Jornalero-​Haus", LocaFra = "(1) Résidence de jornalero", LocaPol = "(1) Dom jornaleros", LocaRus = "(1) Жилье хорналеро", LocaEsp = "(1) Residencia de Jornalero" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColFace)", Group = "(2) New World", Header = "(A7) Anno 1800", IconFileName = "A7_resident_obrera.png", Identifier = "Residence_colony01_tier02", Guid = 101255, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColFace", LocaEng = "(2) Obrero Residence", LocaGer = "(2) Obrero-​Haus", LocaFra = "(2) Résidence d'obrero", LocaPol = "(2) Dom obreros", LocaRus = "(2) Жилье обреро", LocaEsp = "(2) Residencia de Obrero" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColFace)", Group = "(3) Arctic", Header = "(A7) Anno 1800", IconFileName = "A7_resident_Explorers.png", Identifier = "Residence_Arctic_World", Guid = 112091, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColFace", LocaEng = "(1) Explorer Shelter", LocaGer = "(1) Entdecker-​Behausung", LocaFra = "(1) Abri d'exploratrice", LocaPol = "(1) Schronienie odkrywców", LocaRus = "(1) Жилище исследователей", LocaEsp = "(1) Refugio de exploradores" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColFace)", Group = "(3) Arctic", Header = "(A7) Anno 1800", IconFileName = "A7_resident_Technicians.png", Identifier = "Residence_arctic_tier02", Guid = 112652, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColFace", LocaEng = "(2) Technician Shelter", LocaGer = "(2) Techniker-​Behausung", LocaFra = "(2) Abri de technicien", LocaPol = "(2) Schronienie techników", LocaRus = "(2) Жилище техников", LocaEsp = "(2) Refugio de técnico" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColFace)", Group = "(4) Enbesa", Header = "(A7) Anno 1800", IconFileName = "A7_resident_sheperd.png", Identifier = "Residence_Africa_World", Guid = 114436, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColFace", LocaEng = "(1) Shepherd Residence", LocaGer = "(1) Hirtenhaus", LocaFra = "(1) Résidence de Berger", LocaPol = "(1) Dom pasterzy", LocaRus = "(1) Жилье пастухов", LocaEsp = "(1) Residencia de pastores" });
            result.Add(new ExtraPreset { BuildBlockerX = 3, BuildBlockerZ = 3, Faction = "Residences (RoofColFace)", Group = "(4) Enbesa", Header = "(A7) Anno 1800", IconFileName = "A7_resident_elder.png", Identifier = "Residence_colony02_tier02", Guid = 114437, InfluenceRadius = 0, InfluenceRange = 0, Template = "RoofColFace", LocaEng = "(2) Elder Residence", LocaGer = "(2) Ältestenhaus", LocaFra = "(2) Résidence d'Ancien", LocaPol = "(2) Dom starszych", LocaRus = "(2) Жилье старейшин", LocaEsp = "(2) Residencia de ancianas" });
            return result;
        }
    }
}
